# generate-config.ps1 — Generate yuzu-server.cfg with PBKDF2-SHA256 hashed credentials
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File generate-config.ps1 `
#     -ConfigPath "C:\ProgramData\Yuzu Server\yuzu-server.cfg" `
#     -AdminUser admin -AdminPass "MyPassword123" `
#     [-OperatorUser operator -OperatorPass "OpPassword123"]
#
# Compatible with PowerShell 5.1+ (.NET Framework 4.7.2+, ships with Windows 10+)

param(
    [Parameter(Mandatory=$true)][string]$ConfigPath,
    [Parameter(Mandatory=$true)][string]$AdminUser,
    [Parameter(Mandatory=$true)][string]$AdminPass,
    [string]$OperatorUser = "",
    [string]$OperatorPass = ""
)

function New-PBKDF2Entry {
    param(
        [Parameter(Mandatory=$true)][string]$Username,
        [Parameter(Mandatory=$true)][string]$Password,
        [Parameter(Mandatory=$true)][string]$Role
    )

    # 16-byte random salt
    $salt = [byte[]]::new(16)
    $rng = New-Object System.Security.Cryptography.RNGCryptoServiceProvider
    $rng.GetBytes($salt)
    $rng.Dispose()

    # PBKDF2-SHA256, 100000 iterations, 32-byte output (matches server auth.cpp)
    $pbkdf2 = New-Object System.Security.Cryptography.Rfc2898DeriveBytes(
        $Password, $salt, 100000,
        [System.Security.Cryptography.HashAlgorithmName]::SHA256
    )
    $hash = $pbkdf2.GetBytes(32)
    $pbkdf2.Dispose()

    $saltHex = -join ($salt | ForEach-Object { $_.ToString("x2") })
    $hashHex = -join ($hash | ForEach-Object { $_.ToString("x2") })

    return "${Username}:${Role}:${saltHex}:${hashHex}"
}

# Build config content
$lines = @(
    "# Yuzu Server Configuration",
    "# Version: 1",
    "# Format: username:role:salt:hash",
    "# Generated by Yuzu Server installer",
    ""
)

$lines += New-PBKDF2Entry -Username $AdminUser -Password $AdminPass -Role "admin"

if ($OperatorUser -ne "" -and $OperatorPass -ne "") {
    $lines += New-PBKDF2Entry -Username $OperatorUser -Password $OperatorPass -Role "user"
}

# Ensure parent directory exists
$parentDir = Split-Path -Parent $ConfigPath
if ($parentDir -and -not (Test-Path $parentDir)) {
    New-Item -ItemType Directory -Path $parentDir -Force | Out-Null
}

# Write config (UTF-8, no BOM for C++ compatibility)
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllLines($ConfigPath, $lines, $utf8NoBom)

# Set restrictive ACL: Administrators + SYSTEM only
try {
    $acl = New-Object System.Security.AccessControl.FileSecurity
    $acl.SetAccessRuleProtection($true, $false)
    $acl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
        "BUILTIN\Administrators", "FullControl", "Allow")))
    $acl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
        "NT AUTHORITY\SYSTEM", "FullControl", "Allow")))
    Set-Acl -Path $ConfigPath -AclObject $acl
} catch {
    Write-Warning "Could not restrict file permissions: $_"
}

Write-Host "Configuration written to: $ConfigPath"
