/**
 * pii_scan_plugin.cpp — Sensitive-data (PII) discovery plugin for Yuzu.
 *
 * Audits text files against a research-backed ruleset (credit cards,
 * IBAN, ICAO passport MRZ, driver's licences, and national identifiers
 * for ~45 countries — see content/pii-rules/00-manifest.yaml) using
 * RE2 shape matching plus real checksum validation where one exists.
 * Never stores or emits a raw matched value — findings carry a masked
 * value only (see pii_matcher.hpp mask_value()).
 *
 * Actions:
 *   "scan"             — One-shot walk of the configured paths.
 *   "enable_realtime"  — Registers a filesystem trigger so newly-created
 *                         or renamed files under `watch_path` are
 *                         automatically re-scanned. Built on the agent's
 *                         existing filesystem-trigger primitive (mtime
 *                         polling on the watched path) — this reliably
 *                         catches new files appearing under a watched
 *                         directory, but NOT in-place content edits to an
 *                         already-existing file, since a directory's own
 *                         mtime does not change when a file inside it is
 *                         merely rewritten. True on-write detection of
 *                         in-place edits would need the Trigger Engine
 *                         extended with native OS directory-change
 *                         notifications (inotify/ReadDirectoryChangesW/
 *                         FSEvents) — tracked as follow-up core-agent
 *                         work, not implemented here.
 *   "disable_realtime" — Unregisters the trigger for `watch_path`.
 *   "scan_path"         — Internal: the action the realtime trigger
 *                         fires. Not intended for direct operator use,
 *                         but harmless to call directly (just scans the
 *                         given path once).
 *
 * On-access (on-read) scanning is explicitly OUT OF SCOPE — see
 * docs/user-manual/agent-plugins.md's pii_scan entry for why: true
 * on-access interception needs a kernel-level hook (Windows minifilter,
 * Linux fanotify permission events, macOS Endpoint Security AUTH events)
 * that is a categorically different, much larger undertaking than a
 * userspace plugin, and pushes toward exactly the EDR-style capability
 * set Yuzu is deliberately not building (see CLAUDE.md).
 *
 * Params (all actions except "disable_realtime"/"enable_realtime" accept
 * these; "scan_path" receives them forwarded from the trigger config):
 *   paths          — comma-separated list of file/directory paths to scan.
 *   jurisdictions  — comma-separated filter: country codes ("GB", "US"),
 *                    state-prefixed codes ("US-CA"), or region presets
 *                    ("EMEA", "APAC", "AMERICAS"). Empty/absent = no
 *                    filter (every rule applies). Generic rules (credit
 *                    cards, IBAN, email, ...) always apply regardless.
 *   allExtensions  — "true" to scan every file found, ignoring the
 *                    built-in plain-text extension allowlist.
 *   incremental    — "false" to disable the size+mtime fingerprint cache
 *                    (default: enabled — unchanged files are skipped on
 *                    repeat scans without re-reading their content).
 *
 * Output is pipe-delimited via write_output(), one row per finding:
 *   severity|findingConfidence|category|ruleId|filePath|line|maskedValue|complianceTags
 */

#include <yuzu/plugin.hpp>

#include <format>
#include <functional>
#include <optional>
#include <string>
#include <vector>

#include "pii_matcher.hpp"
#include "pii_rules.hpp"
#include "pii_scan_collect.hpp"

namespace yuzu::pii {
extern const std::string_view kEmbeddedPiiRulesJson; // generated by embed_pii_rules.py
}

namespace {

using namespace yuzu::pii;

// ABI v4+ per-action, per-OS capability declaration (#2204) -- read
// directly out of the built plugin binary by tools/capmatrix-gen to
// populate docs/os-capability-matrix.md's generated block. Genuinely
// cross-platform: std::filesystem walk + RE2 match has no per-OS branch,
// and the realtime trigger rides the agent's existing, already
// cross-platform filesystem-trigger primitive (mtime polling).
const YuzuActionDescriptor kActionDescriptors[] = {
    {
        /* .action      = */ "scan",
        /* .linux_leg   = */ {YUZU_SUPPORT_SUPPORTED, 1, "std_filesystem", nullptr},
        /* .macos_leg   = */ {YUZU_SUPPORT_SUPPORTED, 1, "std_filesystem", nullptr},
        /* .windows_leg = */ {YUZU_SUPPORT_SUPPORTED, 1, "std_filesystem", nullptr},
    },
    {
        /* .action      = */ "enable_realtime",
        /* .linux_leg   = */
        {YUZU_SUPPORT_SUPPORTED, 1, "agent_trigger_engine (filesystem mtime poll)",
         "catches new/renamed files under the watched directory, not in-place edits to an "
         "existing file -- see the plugin README's Caveats"},
        /* .macos_leg   = */
        {YUZU_SUPPORT_SUPPORTED, 1, "agent_trigger_engine (filesystem mtime poll)",
         "catches new/renamed files under the watched directory, not in-place edits to an "
         "existing file -- see the plugin README's Caveats"},
        /* .windows_leg = */
        {YUZU_SUPPORT_SUPPORTED, 1, "agent_trigger_engine (filesystem mtime poll)",
         "catches new/renamed files under the watched directory, not in-place edits to an "
         "existing file -- see the plugin README's Caveats"},
    },
    {
        /* .action      = */ "disable_realtime",
        /* .linux_leg   = */ {YUZU_SUPPORT_SUPPORTED, 1, "agent_trigger_engine", nullptr},
        /* .macos_leg   = */ {YUZU_SUPPORT_SUPPORTED, 1, "agent_trigger_engine", nullptr},
        /* .windows_leg = */ {YUZU_SUPPORT_SUPPORTED, 1, "agent_trigger_engine", nullptr},
    },
    {
        /* .action      = */ "scan_path",
        /* .linux_leg   = */ {YUZU_SUPPORT_SUPPORTED, 1, "std_filesystem", nullptr},
        /* .macos_leg   = */ {YUZU_SUPPORT_SUPPORTED, 1, "std_filesystem", nullptr},
        /* .windows_leg = */ {YUZU_SUPPORT_SUPPORTED, 1, "std_filesystem", nullptr},
    },
};

std::string escape_pipes(std::string_view s) {
    std::string out;
    out.reserve(s.size());
    for (char c : s) {
        if (c == '|')
            out += "\\|";
        else
            out += c;
    }
    return out;
}

std::vector<std::string> split_csv(std::string_view s) {
    std::vector<std::string> out;
    size_t start = 0;
    while (start <= s.size()) {
        size_t comma = s.find(',', start);
        std::string_view piece =
            (comma == std::string_view::npos) ? s.substr(start) : s.substr(start, comma - start);
        // trim
        size_t b = piece.find_first_not_of(" \t");
        size_t e = piece.find_last_not_of(" \t");
        if (b != std::string_view::npos)
            out.emplace_back(piece.substr(b, e - b + 1));
        if (comma == std::string_view::npos)
            break;
        start = comma + 1;
    }
    return out;
}

std::string join(const std::vector<std::string>& parts, std::string_view sep) {
    std::string out;
    for (size_t i = 0; i < parts.size(); ++i) {
        if (i)
            out += sep;
        out += parts[i];
    }
    return out;
}

std::string derive_trigger_id(std::string_view watch_path) {
    return std::format("pii_scan_rt_{}", std::hash<std::string>{}(std::string(watch_path)));
}

// ── Shared engine state, built once per execute() call from the embedded
//    ruleset. Rules parsing + RE2 compilation happen every call rather
//    than being cached at plugin scope — pii_scan's actions are invoked
//    rarely (one-shot scans, or realtime-trigger fires that are already
//    debounced by the Trigger Engine), so the cost of re-parsing ~190
//    small JSON objects and re-compiling their regexes is negligible
//    next to the file I/O a scan does, and this keeps the plugin
//    trivially thread-safe (no shared mutable state across concurrent
//    execute() calls on different command IDs — see plugin.hpp's
//    thread-safety contract).
struct Engine {
    std::vector<Rule> rules;
    std::vector<CompiledRule> compiled;
};

Engine build_engine(const std::vector<std::string>& jurisdiction_filter) {
    Engine e;
    e.rules = parse_rules_json(yuzu::pii::kEmbeddedPiiRulesJson);
    if (!jurisdiction_filter.empty())
        e.rules = filter_rules_by_jurisdiction(e.rules, jurisdiction_filter);
    e.compiled = compile_rules(e.rules);
    return e;
}

void output_findings(yuzu::CommandContext& ctx, const std::vector<Finding>& findings,
                     std::string_view file_path) {
    for (const auto& f : findings) {
        ctx.write_output(std::format(
            "{}|{}|{}|{}|{}|{}|{}|{}", f.severity, f.finding_confidence, f.category, f.rule_id,
            escape_pipes(file_path), f.line_number, f.masked_value, join(f.compliance_tags, ";")));
    }
}

// Cheap size+mtime fingerprint — avoids reading unchanged files' content
// on a repeat scan. Not a content hash: two different files could in
// principle share a (size, mtime) pair, in which case we'd skip a
// changed-in-place file with a coincidentally-preserved mtime (rare, and
// no worse than any mtime-based cache); a full content hash would be
// more precise but requires reading the file anyway, defeating the
// purpose of the fast-path skip.
std::string fingerprint(const std::string& path, uint64_t size) {
    std::error_code ec;
    auto mtime = std::filesystem::last_write_time(path, ec);
    auto ticks = ec ? 0 : mtime.time_since_epoch().count();
    return std::format("{}:{}", size, ticks);
}

std::vector<Finding> scan_one_file(yuzu::CommandContext& ctx, yuzu::PluginContext* pctx,
                                   const Engine& engine, const CandidateFile& file, bool incremental) {
    std::string cache_key = std::format("scanned:{}", file.path);
    if (incremental && pctx) {
        std::string fp = fingerprint(file.path, file.size_bytes);
        if (pctx->storage_get(cache_key) == fp) {
            return {}; // unchanged since last scan — skip the read entirely
        }
    }

    auto content = read_file_text(file.path, file.size_bytes);
    std::vector<Finding> findings;
    if (content) {
        findings = scan_text(engine.compiled, *content);
        output_findings(ctx, findings, file.path);
    }

    if (incremental && pctx) {
        pctx->storage_set(cache_key, fingerprint(file.path, file.size_bytes));
    }
    return findings;
}

// `raw_ctx` is the plugin's cached YuzuPluginContext* (see PiiScanPlugin's
// comment on raw_ctx_ below) — storage access is optional (incremental
// caching is skipped, not fatal, if the plugin somehow has none).
void run_scan(yuzu::CommandContext& ctx, YuzuPluginContext* raw_ctx, yuzu::Params params) {
    auto paths = split_csv(params.get("paths", ""));
    auto jurisdictions = split_csv(params.get("jurisdictions", ""));
    bool all_ext = params.get("allExtensions", "false") == "true";
    bool incremental = params.get("incremental", "true") != "false";

    if (paths.empty()) {
        ctx.write_output("ERROR|LOW|config|pii_scan.no_paths||0||No `paths` parameter supplied");
        return;
    }

    std::optional<yuzu::PluginContext> pctx_storage;
    yuzu::PluginContext* pctx = nullptr;
    if (raw_ctx) {
        pctx_storage.emplace(raw_ctx);
        pctx = &*pctx_storage;
    }

    Engine engine = build_engine(jurisdictions);

    ScanConfig cfg;
    cfg.roots = paths;
    cfg.scan_all_extensions = all_ext;

    auto files = enumerate_files(cfg);
    ctx.report_progress(0);
    size_t total_findings = 0;
    for (size_t i = 0; i < files.size(); ++i) {
        total_findings += scan_one_file(ctx, pctx, engine, files[i], incremental).size();
        if (files.size() > 0) {
            ctx.report_progress(static_cast<int>((i + 1) * 100 / files.size()));
        }
    }
    ctx.write_output(std::format("INFO|HIGH|summary|pii_scan.summary||0|{} files scanned, {} findings|",
                                 files.size(), total_findings));
}

} // namespace

class PiiScanPlugin final : public yuzu::Plugin {
public:
    std::string_view name() const noexcept override { return "pii_scan"; }
    std::string_view version() const noexcept override { return "1.0.0"; }
    std::string_view description() const noexcept override {
        return "Sensitive-data (PII) discovery — audits files against a research-backed ruleset "
               "of financial, passport, driver's-licence, and national-ID identifiers with real "
               "checksum validation. Audit-only, never stores raw matched values.";
    }

    const char* const* actions() const noexcept override {
        static const char* acts[] = {"scan", "enable_realtime", "disable_realtime", "scan_path",
                                     nullptr};
        return acts;
    }

    const YuzuActionDescriptor* action_descriptors() const noexcept override {
        return kActionDescriptors;
    }
    size_t action_descriptor_count() const noexcept override {
        return sizeof(kActionDescriptors) / sizeof(kActionDescriptors[0]);
    }

    yuzu::Result<void> init(yuzu::PluginContext& ctx) override {
        // ctx is a stack-local wrapper the C-ABI trampoline destroys the
        // moment init() returns — only its underlying raw() pointer
        // outlives this call (per plugin.hpp's own doc comment: "for
        // caching across calls"). Cache THAT, and re-wrap it fresh in
        // execute() each time storage/trigger access is needed.
        raw_ctx_ = ctx.raw();
        return {};
    }

    void shutdown(yuzu::PluginContext&) noexcept override { raw_ctx_ = nullptr; }

    int execute(yuzu::CommandContext& ctx, std::string_view action, yuzu::Params params) override {
        if (action == "scan" || action == "scan_path") {
            run_scan(ctx, raw_ctx_, params);
            return 0;
        }

        if (action == "enable_realtime") {
            std::string watch_path(params.get("watch_path", ""));
            if (watch_path.empty()) {
                ctx.write_output("ERROR|LOW|config|pii_scan.no_watch_path||0||`watch_path` parameter required");
                return 1;
            }
            std::string jurisdictions(params.get("jurisdictions", ""));
            std::string trigger_id = derive_trigger_id(watch_path);

            // Escape for embedding in the trigger's JSON config — watch_path/
            // jurisdictions are operator-supplied strings, not JSON-safe by
            // construction.
            auto json_escape = [](std::string_view s) {
                std::string out;
                for (char c : s) {
                    if (c == '"' || c == '\\')
                        out += '\\';
                    out += c;
                }
                return out;
            };

            std::string config_json = std::format(
                R"({{"plugin":"pii_scan","action":"scan_path","watch_path":"{0}","parameters":{{"paths":"{0}","jurisdictions":"{1}"}}}})",
                json_escape(watch_path), json_escape(jurisdictions));

            bool ok = false;
            if (raw_ctx_) {
                yuzu::PluginContext pctx{raw_ctx_};
                ok = pctx.register_trigger(trigger_id, "filesystem", config_json);
            }
            ctx.write_output(std::format("{}|HIGH|config|pii_scan.enable_realtime||0|{}|",
                                         ok ? "INFO" : "ERROR",
                                         ok ? "realtime scanning enabled for " + watch_path
                                            : "failed to register trigger"));
            return ok ? 0 : 1;
        }

        if (action == "disable_realtime") {
            std::string watch_path(params.get("watch_path", ""));
            if (watch_path.empty()) {
                ctx.write_output("ERROR|LOW|config|pii_scan.no_watch_path||0||`watch_path` parameter required");
                return 1;
            }
            std::string trigger_id = derive_trigger_id(watch_path);
            bool ok = false;
            if (raw_ctx_) {
                yuzu::PluginContext pctx{raw_ctx_};
                ok = pctx.unregister_trigger(trigger_id);
            }
            ctx.write_output(std::format("{}|HIGH|config|pii_scan.disable_realtime||0|{}|",
                                         ok ? "INFO" : "ERROR",
                                         ok ? "realtime scanning disabled for " + watch_path
                                            : "no active trigger for that path"));
            return ok ? 0 : 1;
        }

        ctx.write_output(std::format("ERROR|LOW|config|pii_scan.unknown_action||0|unknown action: {}|",
                                     action));
        return 1;
    }

private:
    YuzuPluginContext* raw_ctx_ = nullptr;
};

YUZU_PLUGIN_EXPORT(PiiScanPlugin)
