/* ── Compose File Generator ── */

function generate() {
  const config = {
    version: val('yuzu-version'),
    adminUser: val('admin-user'),
    adminPass: val('admin-pass'),
    dashboardPort: num('dashboard-port'),
    grpcPort: num('grpc-port'),
    mgmtPort: num('mgmt-port'),
    gwUpstreamPort: num('gateway-upstream-port'),
    tls: chk('enable-tls'),
    tlsCert: val('tls-cert'),
    tlsKey: val('tls-key'),
    dataDir: val('data-dir'),
    clickhouse: chk('include-clickhouse'),
    chHttpPort: num('ch-http-port'),
    chNativePort: num('ch-native-port'),
    chUser: val('ch-user'),
    chPass: val('ch-pass'),
    chDb: val('ch-db'),
    persistentVolumes: chk('persistent-volumes'),
    prometheus: chk('include-prometheus'),
    promPort: num('prom-port'),
    grafana: chk('include-grafana'),
    grafanaPort: num('grafana-port'),
    grafanaPass: val('grafana-pass'),
    gateway: chk('include-gateway'),
    gwAgentPort: num('gw-agent-port'),
    gwMgmtPort: num('gw-mgmt-port'),
    gwHealthPort: num('gw-health-port'),
    gwMetricsPort: num('gw-metrics-port'),
    gwPoolSize: num('gw-pool-size'),
    gwTls: chk('gw-tls'),
  };

  const compose = generateCompose(config);
  const env = generateEnv(config);

  document.getElementById('compose-output').textContent = compose;
  document.getElementById('env-output').textContent = env;
  document.getElementById('output').style.display = '';
  document.getElementById('output').scrollIntoView({ behavior: 'smooth' });
}

function generateEnv(c) {
  return `# ── Yuzu Environment Variables ──
# Generated by Yuzu Compose Wizard
# Edit this file to reconfigure without touching docker-compose.yml

# Yuzu version (container image tag)
YUZU_VERSION=${c.version}

# ── Server ──
YUZU_DASHBOARD_PORT=${c.dashboardPort}
YUZU_GRPC_PORT=${c.grpcPort}
YUZU_MGMT_PORT=${c.mgmtPort}
YUZU_GATEWAY_UPSTREAM_PORT=${c.gwUpstreamPort}
YUZU_ADMIN_USER=${c.adminUser}
${c.clickhouse ? `YUZU_CLICKHOUSE_PASSWORD=${c.chPass}
YUZU_CLICKHOUSE_DB=${c.chDb}
YUZU_CLICKHOUSE_USER=${c.chUser}` : ''}
${c.prometheus ? `
# ── Prometheus ──
YUZU_PROMETHEUS_PORT=${c.promPort}` : ''}
${c.grafana ? `
# ── Grafana ──
YUZU_GRAFANA_PORT=${c.grafanaPort}
YUZU_GRAFANA_ADMIN_PASSWORD=${c.grafanaPass}` : ''}
${c.gateway ? `
# ── Gateway ──
YUZU_GW_AGENT_PORT=${c.gwAgentPort}
YUZU_GW_MGMT_PORT=${c.gwMgmtPort}
YUZU_GW_HEALTH_PORT=${c.gwHealthPort}
YUZU_GW_METRICS_PORT=${c.gwMetricsPort}` : ''}`;
}

function generateCompose(c) {
  // Admin hash - using the default for admin:admin, with a note for custom passwords
  const adminHash = `admin:admin:ab3585560da45a7b7da0a220c922dd72:25e957743ebefd48d938b30cdd117ef4487897da209e0e8883dd473363dceb8a`;
  // TODO: For custom passwords, users need to run: yuzu-server hash-password <username> <password>

  let y = `## Yuzu Stack — Generated by Yuzu Compose Wizard
##
## Customised for your deployment. Edit .env for quick reconfiguration.
##
## Usage:
##   docker compose up -d
##   docker compose logs -f
##   docker compose down -v    # ⚠️ -v removes data volumes!
##
## Dashboard:   http://localhost:${c.dashboardPort}  (${c.adminUser} / <your-password>)
${c.grafana ? `## Grafana:     http://localhost:${c.grafanaPort}  (admin / ${c.grafanaPass})` : ''}
${c.prometheus ? `## Prometheus:  http://localhost:${c.promPort}` : ''}
${c.clickhouse ? `## ClickHouse:  http://localhost:${c.chHttpPort}  (${c.chUser} / ${c.chPass})` : ''}
##
## Connect an agent:
##   yuzu-agent --server localhost:${c.gateway ? c.gwAgentPort : c.grpcPort} --no-tls
##   (approve the agent in Settings, then restart the agent)
##

`;

  // ── Configs ──
  y += `configs:\n`;
  y += `  # ── Server RBAC config ──\n`;
  y += `  # NOTE: RBAC is enabled but may not enforce in all Yuzu versions.\n`;
  y += `  # See: https://github.com/Tr3kkR/Yuzu/issues/388\n`;
  y += `  server-cfg:\n`;
  y += `    content: |\n`;
  y += `      ${c.adminUser}:${c.adminPass}:ab3585560da45a7b7da0a220c922dd72:25e957743ebefd48d938b30cdd117ef4487897da209e0e8883dd473363dceb8a\n`;
  y += `      \n`;
  y += `      [rbac]\n`;
  y += `      enabled = true\n`;

  if (c.gateway) {
    y += `\n  # ── Gateway (Erlang/OTP) sys.config ──\n`;
    y += `  gateway-sys-config:\n`;
    y += `    content: |\n`;
    y += `      [\n`;
    y += `          {yuzu_gw, [\n`;
    y += `              {agent_listen_addr, "0.0.0.0"},\n`;
    y += `              {agent_listen_port, 50051},\n`;
    y += `              {mgmt_listen_addr, "0.0.0.0"},\n`;
    y += `              {mgmt_listen_port, 50063},\n`;
    y += `              {upstream_addr, "server"},\n`;
    y += `              {upstream_port, ${c.gwUpstreamPort}},\n`;
    y += `              {upstream_pool_size, ${c.gwPoolSize}},\n`;
    y += `              {heartbeat_batch_interval_ms, 1000},\n`;
    y += `              {default_command_timeout_s, 300},\n`;
    y += `              {prometheus_port, 9568},\n`;
    y += `              {health_port, 8081},\n`;
    y += `              {telemetry_gauge_interval_ms, 10000},\n`;
    y += `              {circuit_breaker_failure_threshold, 5},\n`;
    y += `              {circuit_breaker_reset_timeout_ms, 10000},\n`;
    y += `              {circuit_breaker_max_reset_timeout_ms, 300000},\n`;
    y += `              {backpressure_threshold, 1000},\n`;
    y += `              {hash_ring_vnodes, 256}\n`;
    y += `          ]},\n`;
    y += `          {grpcbox, [\n`;
    y += `              {client, #{channels => [\n`;
    y += `                  {default_channel, [{http, "server", ${c.gwUpstreamPort}, []}], #{}}\n`;
    y += `              ]}},\n`;
    y += `              {servers, [\n`;
    y += `                  #{grpc_opts => #{\n`;
    y += `                      service_protos => [agent_pb],\n`;
    y += `                      services => #{'yuzu.agent.v1.AgentService' => yuzu_gw_agent_service}\n`;
    y += `                  },\n`;
    y += `                  listen_opts => #{port => 50051, ip => {0,0,0,0}}},\n`;
    y += `                  #{grpc_opts => #{\n`;
    y += `                      service_protos => [management_pb],\n`;
    y += `                      services => #{'yuzu.server.v1.ManagementService' => yuzu_gw_mgmt_service}\n`;
    y += `                  },\n`;
    y += `                  listen_opts => #{port => 50063, ip => {0,0,0,0}}}\n`;
    y += `              ]}\n`;
    y += `          ]},\n`;
    y += `          {kernel, [\n`;
    y += `              {connect_all, false},\n`;
    y += `              {net_ticktime, 30},\n`;
    y += `              {logger_level, info},\n`;
    y += `              {logger, [\n`;
    y += `                  {handler, default, logger_std_h, #{\n`;
    y += `                      level => info,\n`;
    y += `                      formatter => {logger_formatter, #{\n`;
    y += `                          template => [time, " [", level, "] ", pid, " ", msg, "\\n"]\n`;
    y += `                      }}\n`;
    y += `                  }}\n`;
    y += `              ]}\n`;
    y += `          ]}\n`;
    y += `      ].\n`;
  }

  if (c.prometheus) {
    y += `\n  # ── Prometheus config ──\n`;
    y += `  prometheus-config:\n`;
    y += `    content: |\n`;
    y += `      global:\n`;
    y += `        scrape_interval: 15s\n`;
    y += `        evaluation_interval: 15s\n`;
    y += `      scrape_configs:\n`;
    y += `        - job_name: 'yuzu-server'\n`;
    y += `          metrics_path: '/metrics'\n`;
    y += `          static_configs:\n`;
    y += `            - targets: ['server:8080']\n`;
    y += `              labels:\n`;
    y += `                component: 'server'\n`;
    if (c.gateway) {
      y += `        - job_name: 'yuzu-gateway'\n`;
      y += `          metrics_path: '/metrics'\n`;
      y += `          static_configs:\n`;
      y += `            - targets: ['gateway:9568']\n`;
      y += `              labels:\n`;
      y += `                component: 'gateway'\n`;
    }
  }

  if (c.grafana) {
    y += `\n  # ── Grafana provisioning ──\n`;
    y += `  grafana-datasource:\n`;
    y += `    content: |\n`;
    y += `      apiVersion: 1\n`;
    y += `      datasources:\n`;
    y += `        - name: Prometheus\n`;
    y += `          type: prometheus\n`;
    y += `          access: proxy\n`;
    y += `          url: http://prometheus:9090\n`;
    y += `          isDefault: true\n`;
    y += `          editable: false\n`;
    y += `  grafana-dashboard-provider:\n`;
    y += `    content: |\n`;
    y += `      apiVersion: 1\n`;
    y += `      providers:\n`;
    y += `        - name: Yuzu\n`;
    y += `          orgId: 1\n`;
    y += `          folder: Yuzu\n`;
    y += `          type: file\n`;
    y += `          disableDeletion: false\n`;
    y += `          editable: true\n`;
    y += `          options:\n`;
    y += `            path: /var/lib/grafana/dashboards\n`;
    y += `            foldersFromFilesStructure: false\n`;
    y += `  # Dashboard JSON files — requires deploy/grafana/ in your Yuzu checkout\n`;
    y += `  grafana-dashboard-main:\n`;
    y += `    file: deploy/grafana/yuzu-dashboard.json\n`;
    y += `  grafana-dashboard-fleet:\n`;
    y += `    file: deploy/grafana/yuzu-fleet-dashboard.json\n`;
    y += `  grafana-dashboard-gateway:\n`;
    y += `    file: deploy/grafana/yuzu-gateway-dashboard.json\n`;
    y += `  grafana-dashboard-analytics:\n`;
    y += `    file: deploy/grafana/yuzu-analytics-dashboard.json\n`;
  }

  if (c.clickhouse) {
    y += `\n  # ── ClickHouse init SQL ──\n`;
    y += `  clickhouse-init:\n`;
    y += `    content: |\n`;
    y += `      CREATE DATABASE IF NOT EXISTS ${c.chDb};\n`;
    y += `      CREATE TABLE IF NOT EXISTS ${c.chDb}.yuzu_events (\n`;
    y += `          tenant_id       LowCardinality(String)  DEFAULT 'default',\n`;
    y += `          agent_id        String                  DEFAULT '',\n`;
    y += `          session_id      String                  DEFAULT '',\n`;
    y += `          event_type      LowCardinality(String),\n`;
    y += `          event_time      DateTime64(3, 'UTC'),\n`;
    y += `          ingest_time     DateTime64(3, 'UTC')    DEFAULT now64(3),\n`;
    y += `          plugin          LowCardinality(String)  DEFAULT '',\n`;
    y += `          capability      LowCardinality(String)  DEFAULT '',\n`;
    y += `          correlation_id  String                  DEFAULT '',\n`;
    y += `          severity        Enum8('debug'=0,'info'=1,'warn'=2,'error'=3,'critical'=4) DEFAULT 'info',\n`;
    y += `          source          LowCardinality(String)  DEFAULT 'server',\n`;
    y += `          hostname        String                  DEFAULT '',\n`;
    y += `          os              LowCardinality(String)  DEFAULT '',\n`;
    y += `          arch            LowCardinality(String)  DEFAULT '',\n`;
    y += `          agent_version   LowCardinality(String)  DEFAULT '',\n`;
    y += `          principal       String                  DEFAULT '',\n`;
    y += `          principal_role  LowCardinality(String)  DEFAULT '',\n`;
    y += `          attributes      String                  DEFAULT '{}',\n`;
    y += `          payload         String                  DEFAULT '{}',\n`;
    y += `          schema_version  UInt8                   DEFAULT 1\n`;
    y += `      ) ENGINE = MergeTree()\n`;
    y += `        PARTITION BY toYYYYMM(event_time)\n`;
    y += `        ORDER BY (tenant_id, event_type, event_time, agent_id)\n`;
    y += `        TTL toDate(event_time) + INTERVAL 365 DAY;\n`;
    y += `      ALTER TABLE ${c.chDb}.yuzu_events ADD INDEX IF NOT EXISTS idx_agent_id agent_id TYPE bloom_filter GRANULARITY 4;\n`;
    y += `      ALTER TABLE ${c.chDb}.yuzu_events ADD INDEX IF NOT EXISTS idx_correlation_id correlation_id TYPE bloom_filter GRANULARITY 4;\n`;
    y += `      ALTER TABLE ${c.chDb}.yuzu_events ADD INDEX IF NOT EXISTS idx_hostname hostname TYPE bloom_filter GRANULARITY 4;\n`;
    y += `      CREATE MATERIALIZED VIEW IF NOT EXISTS ${c.chDb}.mv_command_duration_hourly\n`;
    y += `      ENGINE = AggregatingMergeTree()\n`;
    y += `      PARTITION BY toYYYYMM(hour)\n`;
    y += `      ORDER BY (tenant_id, plugin, hour)\n`;
    y += `      AS SELECT\n`;
    y += `          tenant_id, plugin,\n`;
    y += `          toStartOfHour(event_time) AS hour,\n`;
    y += `          quantileState(0.5)(JSONExtractFloat(payload, 'duration_ms'))  AS p50,\n`;
    y += `          quantileState(0.95)(JSONExtractFloat(payload, 'duration_ms')) AS p95,\n`;
    y += `          quantileState(0.99)(JSONExtractFloat(payload, 'duration_ms')) AS p99,\n`;
    y += `          countState() AS total\n`;
    y += `      FROM ${c.chDb}.yuzu_events\n`;
    y += `      WHERE event_type = 'command.completed'\n`;
    y += `      GROUP BY tenant_id, plugin, hour;\n`;
    y += `      CREATE MATERIALIZED VIEW IF NOT EXISTS ${c.chDb}.mv_agent_activity_daily\n`;
    y += `      ENGINE = SummingMergeTree()\n`;
    y += `      PARTITION BY toYYYYMM(day)\n`;
    y += `      ORDER BY (tenant_id, agent_id, day, event_type)\n`;
    y += `      AS SELECT\n`;
    y += `          tenant_id, agent_id,\n`;
    y += `          toDate(event_time) AS day,\n`;
    y += `          event_type,\n`;
    y += `          count() AS event_count\n`;
    y += `      FROM ${c.chDb}.yuzu_events\n`;
    y += `      GROUP BY tenant_id, agent_id, day, event_type;\n`;
  }

  // ── Services ──
  y += `\nservices:\n`;

  // Yuzu Server
  y += `  # ── Yuzu Server ──────────────────────────────────────────────────────\n`;
  y += `  server:\n`;
  y += `    image: ghcr.io/tr3kkr/yuzu-server:\${YUZU_VERSION:-${c.version}}\n`;
  y += `    container_name: yuzu-server\n`;
  y += `    restart: unless-stopped\n`;
  y += `    ports:\n`;
  y += `      - "${c.dashboardPort}:8080"     # Web dashboard + REST API\n`;
  y += `      - "${c.grpcPort}:50051"   # Agent gRPC (direct-connect agents)\n`;
  y += `      - "${c.mgmtPort}:50052"   # Management gRPC\n`;
  y += `      - "${c.gwUpstreamPort}:${c.gwUpstreamPort}"   # Gateway upstream\n`;
  y += `    environment:\n`;
  y += `      - YUZU_LOG_LEVEL=info\n`;
  y += `      - YUZU_LOG_FORMAT=json\n`;
  y += `    command:\n`;
  y += `      - "--listen"\n`;
  y += `      - "0.0.0.0:50051"\n`;
  if (c.tls) {
    y += `      - "--cert"\n`;
    y += `      - "${c.tlsCert}"\n`;
    y += `      - "--key"\n`;
    y += `      - "${c.tlsKey}"\n`;
  } else {
    y += `      - "--no-tls"\n`;
    y += `      - "--no-https"\n`;
  }
  y += `      - "--web-address"\n`;
  y += `      - "0.0.0.0"\n`;
  y += `      - "--web-port"\n`;
  y += `      - "8080"\n`;
  y += `      - "--config"\n`;
  y += `      - "/etc/yuzu/yuzu-server.cfg"\n`;
  y += `      - "--data-dir"\n`;
  y += `      - "${c.dataDir}"\n`;
  y += `      # ⚠️ --data-dir is REQUIRED. Without it, SQLite stores fail silently.\n`;
  if (c.gateway) {
    y += `      - "--gateway-upstream"\n`;
    y += `      - "0.0.0.0:${c.gwUpstreamPort}"\n`;
    y += `      - "--gateway-mode"\n`;
    y += `      - "--gateway-command-addr"\n`;
    y += `      - "gateway:50063"\n`;
  }
  y += `      - "--metrics-no-auth"\n`;
  if (c.clickhouse) {
    y += `      - "--clickhouse-url"\n`;
    y += `      - "http://clickhouse:8123"\n`;
    y += `      - "--clickhouse-database"\n`;
    y += `      - "${c.chDb}"\n`;
    y += `      - "--clickhouse-table"\n`;
    y += `      - "yuzu_events"\n`;
    y += `      - "--clickhouse-user"\n`;
    y += `      - "${c.chUser}"\n`;
    y += `      - "--clickhouse-password"\n`;
    y += `      - "${c.chPass}"\n`;
  }
  y += `    configs:\n`;
  y += `      - source: server-cfg\n`;
  y += `        target: /etc/yuzu/yuzu-server.cfg\n`;
  y += `    volumes:\n`;
  if (c.persistentVolumes) {
    y += `      - server-data:${c.dataDir}\n`;
  } else {
    y += `      - ${c.dataDir}\n`;
  }
  y += `    healthcheck:\n`;
  y += `      test: ["CMD", "curl", "-sf", "http://localhost:8080/livez"]\n`;
  y += `      interval: 10s\n`;
  y += `      timeout: 5s\n`;
  y += `      retries: 5\n`;
  if (c.clickhouse) {
    y += `    depends_on:\n`;
    y += `      clickhouse:\n`;
    y += `        condition: service_healthy\n`;
  }

  // Gateway
  if (c.gateway) {
    y += `\n  # ── Yuzu Gateway (Erlang/OTP) ────────────────────────────────────────\n`;
    y += `  gateway:\n`;
    y += `    image: ghcr.io/tr3kkr/yuzu-gateway:\${YUZU_VERSION:-${c.version}}\n`;
    y += `    container_name: yuzu-gateway\n`;
    y += `    restart: unless-stopped\n`;
    y += `    ports:\n`;
    y += `      - "${c.gwAgentPort}:50051"   # Agent-facing gRPC (mapped to avoid conflict with server)\n`;
    y += `      - "${c.gwMgmtPort}:50063"   # Management/command forwarding\n`;
    y += `      - "${c.gwHealthPort}:8081"     # Health/readiness\n`;
    y += `      - "${c.gwMetricsPort}:9568"     # Prometheus metrics\n`;
    y += `    environment:\n`;
    y += `      - YUZU_GW_TLS_ENABLED=${c.gwTls ? 'true' : 'false'}\n`;
    y += `    configs:\n`;
    y += `      - source: gateway-sys-config\n`;
    y += `        target: /opt/yuzu_gw/releases/0.2.0/sys.config\n`;
    y += `    healthcheck:\n`;
    y += `      test: ["CMD-SHELL", "echo > /dev/tcp/localhost/8081"]\n`;
    y += `      interval: 10s\n`;
    y += `      timeout: 5s\n`;
    y += `      retries: 5\n`;
  }

  // Prometheus
  if (c.prometheus) {
    y += `\n  # ── Prometheus ───────────────────────────────────────────────────────\n`;
    y += `  prometheus:\n`;
    y += `    image: prom/prometheus:latest\n`;
    y += `    container_name: yuzu-prometheus\n`;
    y += `    restart: unless-stopped\n`;
    y += `    ports:\n`;
    y += `      - "${c.promPort}:9090"\n`;
    y += `    configs:\n`;
    y += `      - source: prometheus-config\n`;
    y += `        target: /etc/prometheus/prometheus.yml\n`;
    y += `    volumes:\n`;
    y += `      - prometheus-data:/prometheus\n`;
    y += `    depends_on:\n`;
    y += `      - server\n`;
    if (c.gateway) y += `      - gateway\n`;
  }

  // Grafana
  if (c.grafana) {
    y += `\n  # ── Grafana ──────────────────────────────────────────────────────────\n`;
    y += `  grafana:\n`;
    y += `    image: grafana/grafana:latest\n`;
    y += `    container_name: yuzu-grafana\n`;
    y += `    restart: unless-stopped\n`;
    y += `    ports:\n`;
    y += `      - "${c.grafanaPort}:3000"\n`;
    y += `    environment:\n`;
    y += `      - GF_SECURITY_ADMIN_PASSWORD=${c.grafanaPass}\n`;
    y += `    configs:\n`;
    y += `      - source: grafana-datasource\n`;
    y += `        target: /etc/grafana/provisioning/datasources/prometheus.yml\n`;
    y += `      - source: grafana-dashboard-provider\n`;
    y += `        target: /etc/grafana/provisioning/dashboards/yuzu.yml\n`;
    y += `      - source: grafana-dashboard-main\n`;
    y += `        target: /var/lib/grafana/dashboards/yuzu-dashboard.json\n`;
    y += `      - source: grafana-dashboard-fleet\n`;
    y += `        target: /var/lib/grafana/dashboards/yuzu-fleet-dashboard.json\n`;
    y += `      - source: grafana-dashboard-gateway\n`;
    y += `        target: /var/lib/grafana/dashboards/yuzu-gateway-dashboard.json\n`;
    y += `      - source: grafana-dashboard-analytics\n`;
    y += `        target: /var/lib/grafana/dashboards/yuzu-analytics-dashboard.json\n`;
    y += `    volumes:\n`;
    y += `      - grafana-data:/var/lib/grafana\n`;
    y += `    depends_on:\n`;
    y += `      - prometheus\n`;
  }

  // ClickHouse
  if (c.clickhouse) {
    y += `\n  # ── ClickHouse ───────────────────────────────────────────────────────\n`;
    y += `  clickhouse:\n`;
    y += `    image: clickhouse/clickhouse-server:latest\n`;
    y += `    container_name: yuzu-clickhouse\n`;
    y += `    restart: unless-stopped\n`;
    y += `    ports:\n`;
    y += `      - "${c.chHttpPort}:8123"     # HTTP interface\n`;
    y += `      - "${c.chNativePort}:9000"     # Native protocol\n`;
    y += `    environment:\n`;
    y += `      - CLICKHOUSE_DB=${c.chDb}\n`;
    y += `      - CLICKHOUSE_USER=${c.chUser}\n`;
    y += `      - CLICKHOUSE_PASSWORD=${c.chPass}\n`;
    y += `    configs:\n`;
    y += `      - source: clickhouse-init\n`;
    y += `        target: /docker-entrypoint-initdb.d/init.sql\n`;
    y += `    volumes:\n`;
    y += `      - clickhouse-data:/var/lib/clickhouse\n`;
    y += `    ulimits:\n`;
    y += `      nofile:\n`;
    y += `        soft: 262144\n`;
    y += `        hard: 262144\n`;
    y += `    healthcheck:\n`;
    y += `      test: ["CMD", "clickhouse-client", "--password", "${c.chPass}", "-q", "SELECT 1"]\n`;
    y += `      interval: 10s\n`;
    y += `      timeout: 5s\n`;
    y += `      retries: 5\n`;
  }

  // Volumes
  if (c.persistentVolumes) {
    y += `\nvolumes:\n`;
    y += `  server-data:\n`;
    if (c.prometheus) y += `  prometheus-data:\n`;
    if (c.grafana) y += `  grafana-data:\n`;
    if (c.clickhouse) y += `  clickhouse-data:\n`;
  }

  return y;
}