#pragma once

#include <sqlite3.h>

#include <cstddef>
#include <cstdint>
#include <expected>
#include <filesystem>
#include <optional>
#include <shared_mutex>
#include <string>
#include <unordered_set>
#include <vector>

namespace yuzu::server {

// Server-side storage for Guardian **Baselines** — the named, deployable
// collection of Guards. See docs/guardian-baseline-model.md (resolved model)
// and docs/guardian-mvp-contract.md §6/§7 (frozen contract; G10's single-scope
// targeting is superseded by the baseline-model doc — assignment is now
// included − excluded management groups).
//
// Model recap (what this store persists):
//   - A Baseline groups one or more Guards (M:N, via guaranteed_state_baseline_rules)
//     and carries an ASSIGNMENT: a set of *included* minus *excluded* management
//     groups (guaranteed_state_baseline_groups; exclude wins, whole-Baseline grain).
//   - The Baseline is the ONLY deployable unit — individual Guards are never
//     deployed on their own (same shape as a GPO / Intune baseline / Jamf
//     Configuration Profile). Deploy is a separate, later slice; this store is
//     pure control-plane config with no engine dependency.
//   - Lifecycle is draft ↔ deployed (MVP). `deployed_snapshot` holds the member
//     set captured at the last deploy and is the ENFORCED set — the push/reconcile
//     gate reads it via deployed_member_rule_ids(), and the detail renderer diffs
//     it against live members for the "re-deploy to apply" flag.
//
// Cross-store references (deliberate, no in-DB foreign key):
//   - A member row's `rule_id` points at a Guard in `guaranteed-state.db`, and an
//     assignment row's `group_id` points at a management group in the management
//     group store's database — DIFFERENT SQLite files, so a real `REFERENCES`
//     foreign key is impossible. A membership/assignment row whose target Guard
//     or group has since been deleted is HARMLESS at deploy time (the push
//     builder resolves member Guards from the Guard store and simply skips one
//     that no longer exists). For config integrity we still expose application-
//     level cleanup hooks — remove_rule_everywhere() / remove_group_everywhere()
//     — for the Guard-delete and group-delete paths to call in a later slice.
//   - The join tables DO carry an in-DB foreign key to `guaranteed_state_baselines`
//     (same file) with ON DELETE CASCADE, so delete_baseline() tears down its own
//     members + assignment atomically, and inserting a join row for a non-existent
//     baseline is rejected by the FK.
//
// Unlike the Guard EVENT store this is bounded operator-authored config (not a
// multi-GB/day stream), so there is deliberately NO retention reaper / cleanup
// thread here.

// Lifecycle states for a Baseline.
inline constexpr const char* kBaselineDraft = "draft";
inline constexpr const char* kBaselineDeployed = "deployed";

// Disposition of a management group within a Baseline's assignment.
inline constexpr const char* kAssignInclude = "include";
inline constexpr const char* kAssignExclude = "exclude";

struct Baseline {
    std::string baseline_id;       // 12-hex, generated by the store when empty on create
    std::string name;              // unique, human-authored
    std::string description;
    std::string lifecycle{kBaselineDraft}; // "draft" | "deployed"
    // JSON array of member rule_ids captured at the last deploy — the set the
    // fleet ACTUALLY enforces (see deployed_member_rule_ids()), distinct from the
    // live member set which may have been edited since (those draft edits enforce
    // only after a Push-gated re-deploy rewrites this). Written by deploy_baseline
    // (guardian_routes.cpp) as nlohmann::json(get_members()).dump(); the detail
    // renderer diffs it against live members to flag "members changed — re-deploy
    // to apply" (baseline_members_drifted). Empty until first deploy.
    std::string deployed_snapshot;
    std::string created_by;
    std::string updated_by;
    std::string deployed_by;       // principal of the last deploy; empty if never deployed
    int64_t created_at{0};         // epoch seconds
    int64_t updated_at{0};         // epoch seconds
    int64_t deployed_at{0};        // epoch seconds of last deploy; 0 if never deployed
};

// A management-group reference in a Baseline's assignment.
struct BaselineGroupAssignment {
    std::string group_id;
    std::string disposition;       // "include" | "exclude"
};

class BaselineStore {
public:
    explicit BaselineStore(const std::filesystem::path& db_path);
    ~BaselineStore();

    BaselineStore(const BaselineStore&) = delete;
    BaselineStore& operator=(const BaselineStore&) = delete;

    bool is_open() const;

    // ── Baseline CRUD ──────────────────────────────────────────────────────
    // create_baseline generates a 12-hex baseline_id when `b.baseline_id` is
    // empty and returns the id that was used. A duplicate name (or a caller-
    // supplied duplicate id) is reported with `kConflictPrefix` so REST handlers
    // map it to HTTP 409 via is_conflict_error() — see store_errors.hpp.
    std::expected<std::string, std::string> create_baseline(const Baseline& b);
    std::optional<Baseline> get_baseline(const std::string& baseline_id) const;
    std::vector<Baseline> list_baselines() const;
    // Updates the mutable scalar fields (name, description, lifecycle,
    // deployed_snapshot, deployed_by/at, updated_by) of an existing Baseline.
    // Members + assignment are managed by their own methods. Unknown id is a
    // non-conflict error; a name collision is a kConflictPrefix error.
    std::expected<void, std::string> update_baseline(const Baseline& b);
    // Deletes the Baseline and (via ON DELETE CASCADE) its member + assignment
    // rows. Unknown id is a non-conflict error.
    std::expected<void, std::string> delete_baseline(const std::string& baseline_id);

    // ── Member Guards (M:N) ────────────────────────────────────────────────
    // Replace the ENTIRE member set in one transaction (the create/edit form
    // posts the whole list). Duplicate rule_ids in `rule_ids` are de-duplicated.
    // The baseline must exist (enforced by the join table's FK).
    std::expected<void, std::string> set_members(const std::string& baseline_id,
                                                  const std::vector<std::string>& rule_ids);
    // Member rule_ids for a Baseline, sorted for a stable UI order.
    std::vector<std::string> get_members(const std::string& baseline_id) const;
    // Which Baselines list this Guard as a member? (Reverse lookup the deploy /
    // reconciliation slice needs to recompute affected agents when a Guard
    // changes.) Returns baseline_ids.
    std::vector<std::string> baselines_containing_rule(const std::string& rule_id) const;
    // Cross-store cleanup hook: drop `rule_id` from EVERY Baseline's membership.
    // For the Guard-delete path to call (Guards live in a different database, so
    // no in-DB cascade is possible). Returns the number of membership rows removed.
    std::size_t remove_rule_everywhere(const std::string& rule_id);

    // ── Assignment (included − excluded management groups) ──────────────────
    // Replace the ENTIRE assignment in one transaction. Each entry's disposition
    // must be "include" or "exclude" (validated; an invalid value aborts without
    // writing). Duplicate group_ids collapse to the LAST disposition seen. The
    // baseline must exist (enforced by the FK).
    std::expected<void, std::string>
    set_assignment(const std::string& baseline_id,
                   const std::vector<BaselineGroupAssignment>& groups);
    // The Baseline's assignment, sorted (include before exclude, then group_id).
    std::vector<BaselineGroupAssignment> get_assignment(const std::string& baseline_id) const;
    // Cross-store cleanup hook for management-group deletion (different database).
    // Returns the number of assignment rows removed.
    std::size_t remove_group_everywhere(const std::string& group_id);

    // ── Reverse lookups for the deploy slice ────────────────────────────────
    // All Baselines currently in "deployed" lifecycle — the set the per-device
    // reconciliation deploy unions over.
    std::vector<Baseline> list_deployed_baselines() const;

    // The Baseline gate's input: the union of member rule_ids across every
    // *deployed* Baseline, sourced from each one's deployed_snapshot — i.e. the
    // set that was deployed, NOT the live member set. Editing a deployed
    // Baseline's members is a draft change that reaches agents only after a
    // Push-gated re-deploy rewrites the snapshot; sourcing live members here would
    // let a Write-without-Push principal change fleet enforcement and would
    // diverge from the dashboard's "re-deploy to apply" flag. A malformed or
    // empty snapshot contributes nothing (fail-closed). Computed under one shared
    // lock (no per-Baseline round-trip).
    std::unordered_set<std::string> deployed_member_rule_ids() const;

    // The deployed member rule_ids of ONE Baseline (its `deployed_snapshot` — the
    // enforced set captured at last deploy), sorted + de-duplicated. Per-Baseline
    // analog of the fleet-union overload above; same fail-closed parse (a draft /
    // never-deployed / empty / malformed snapshot yields {}). Backs the
    // baseline-anchored per-device Guardian status REST view.
    std::vector<std::string> deployed_member_rule_ids(const std::string& baseline_id) const;

    // ── Counting (metrics / UI) ─────────────────────────────────────────────
    std::size_t baseline_count() const;
    std::size_t member_count(const std::string& baseline_id) const;

private:
    sqlite3* db_{nullptr};
    mutable std::shared_mutex mtx_;

    void create_tables();
    std::string generate_id() const;
};

} // namespace yuzu::server
