#pragma once

// Build-time embeds of content/ (bundled_content.cpp, generated by
// server/core/scripts/embed_content.py — never edit that TU by hand). One
// declaration site for every consumer, so a change to the emitter's element
// type cannot link cleanly against a stale hand-written extern.

#include <string>
#include <vector>

namespace yuzu::server {

/// content/definitions/**/*.yaml — one JSON envelope per InstructionDefinition.
extern const std::vector<std::string> kBundledDefinitions;
/// content/packs/**/*sets*.yaml — one JSON envelope per InstructionSet.
extern const std::vector<std::string> kBundledSets;
/// content/plugin-docs/*.json — one manifest per plugin README that has
/// adopted docs/plugin-readme-standard.md (rule 10), name-sorted; may be empty.
extern const std::vector<std::string> kBundledPluginDocs;

} // namespace yuzu::server
