#include "product_pack_store.hpp"
#include "store_errors.hpp"

#include "pg/pg_exec.hpp"
#include "pg/pg_migration_runner.hpp"
#include "pg/pg_pool.hpp"
#include "pg/pg_raii.hpp"
#include "utf8_sanitize.hpp"

#include <yuzu/metrics.hpp>

#include <libpq-fe.h>
#include <spdlog/spdlog.h>

#include <atomic>
#include <chrono>
#include <cstdio>
#include <format>
#include <random>
#include <unordered_set>

// Ed25519 signature verification — OpenSSL EVP on every platform.
// Pre-#802 / W7.4 R3, the Windows branch used BCrypt
// (BCRYPT_ECDSA_ALGORITHM + BCRYPT_ECC_CURVE_25519). That combination
// is **ECDSA over curve25519**, NOT **Ed25519/EdDSA** — they are
// different signature schemes with different byte layouts. The
// production code on Windows could therefore never verify a signature
// generated by the Linux/macOS OpenSSL path (which uses real Ed25519
// via EVP_PKEY_ED25519). The bug stayed dormant because the verify
// path had zero production callers until #802 flipped
// require_signed_packs_ to true by default; the W7.4 R1 positive
// signed-pack test (test_product_pack_store.cpp `correctly signed
// pack installs`) exercises a cross-platform verify and surfaced the
// mismatch on the first MSVC CI run. OpenSSL is an unconditional
// vcpkg dependency on every platform (see vcpkg.json + CLAUDE.md
// "OpenSSL is a required dependency on every platform including
// Windows"), so the single OpenSSL path is the correct fix.
#include <openssl/evp.h>

namespace yuzu::server {

// ── Small helpers ────────────────────────────────────────────────────────────

namespace {

constexpr const char* kStoreName = "product_pack_store";

// Bounded acquires (ADR-0012 §2(a)): authoritative store, so reads/writes wait a little longer
// than a fail-soft store's hot-path budget, but every runtime acquire is still bounded.
constexpr std::chrono::milliseconds kReadTimeout{2000};
constexpr std::chrono::milliseconds kWriteTimeout{4000};

// Gate 8 review of F035 (security-guardian/architect, both BLOCKING; same race RbacStore hit
// and fixed as HIGH — CHAOS-1, see rbac_store.cpp's kRevokeCoordLockSql comment for the full
// mechanism): originally serialized uninstall()'s delete+tombstone against
// migrate_from_sqlite's tombstone-check-then-insert (two separate READ COMMITTED statement
// snapshots could otherwise let a concurrent backfill resurrect a pack uninstall() had just
// tombstoned). migrate_from_sqlite is retired (#3623), so that specific race no longer has a
// second writer to race against — kept in place as a no-longer-strictly-necessary but harmless
// serialization of uninstall() against itself; removing it is a separate, undecided question
// this removal deliberately does not resolve. Coarse-grained (one fixed key, not per-pack-id):
// product pack install/uninstall is operator-driven content-catalog management, never a hot
// path, so store-wide serialization is cheap — same reasoning as RbacStore's coordination lock.
// Two-int32 form + the "yuzu" namespace constant matches house convention
// (pg_migration_runner.cpp, auth_db.cpp, secret_codec.cpp, kek_op_lock.hpp, rbac_store.cpp).
constexpr const char* kErasureCoordLockSql =
    "SELECT pg_advisory_xact_lock(2037545589, hashtext('product_pack_store:erasure_coordination'))";

// Preserves the pre-migration SQLite behavior ("generous default, effectively no hard cap") in
// a form Postgres accepts — SQLite treats a non-positive LIMIT as "no limit"; Postgres errors on
// a negative LIMIT. A hostile `?limit=-1` must clamp to the default, never surface as a 503.
constexpr int kDefaultListLimit = 100;
constexpr int kMaxListLimit = 10000;

int64_t now_epoch() {
    return std::chrono::duration_cast<std::chrono::seconds>(
               std::chrono::system_clock::now().time_since_epoch())
        .count();
}

// ── Read-degrade observability (#1675 convention, mirrors CustomPropertiesStore) ──
constexpr const char* kReasonStoreNotOpen = "store_not_open";
constexpr const char* kReasonPoolTimeout = "pool_acquire_timeout";
constexpr const char* kReasonQueryError = "query_error";
constexpr std::uint64_t kReadDegradeLogSample = 100;
constexpr std::int64_t kDegradeEpisodeGapSecs = 60;

struct DegradeSampler {
    std::atomic<std::uint64_t> count{0};
    std::atomic<std::int64_t> last_ts{0};
};

bool note_read_degrade(yuzu::MetricsRegistry* metrics, const char* reason, DegradeSampler& s) {
    if (metrics)
        metrics->counter("yuzu_server_product_pack_read_degrade_total", {{"reason", reason}})
            .increment();
    const std::int64_t now = now_epoch();
    const std::int64_t prev = s.last_ts.exchange(now, std::memory_order_relaxed);
    const std::uint64_t n = s.count.fetch_add(1, std::memory_order_relaxed) + 1;
    const bool new_episode = prev == 0 || (now - prev) > kDegradeEpisodeGapSecs;
    return new_episode || (n % kReadDegradeLogSample) == 0;
}

// One sampler per distinct read call site (a shared sampler would let a hot `list()` degrade
// mask a cold `get()` one from ever logging).
DegradeSampler g_list_sampler;
DegradeSampler g_get_sampler;

std::string gen_id() {
    static thread_local std::mt19937_64 rng(std::random_device{}());
    std::uniform_int_distribution<uint64_t> dist;
    auto hi = dist(rng);
    auto lo = dist(rng);
    char buf[33];
    std::snprintf(buf, sizeof(buf), "%016llx%016llx", static_cast<unsigned long long>(hi),
                  static_cast<unsigned long long>(lo));
    return std::string(buf, 32);
}

/// Strip control characters (newlines, ANSI escapes, NUL, etc.) from a string
/// before it is interpolated into an spdlog line. The pack `name` field is
/// attacker-controlled YAML — without this scrubbing, a pack with
/// `name: "evil\n[INFO] admin login OK\n\033[2K"` would inject forged log
/// lines and terminal escape sequences into operator log files (UP-4 from
/// W7.4 Gate 4). Replaces any byte < 0x20 or == 0x7F with `?`. The result
/// is for human-readable logging only; the verbatim name is preserved in
/// the error envelope returned to REST (where nlohmann::json::dump escapes
/// it safely) and in the stored `name` column.
std::string sanitize_for_log(std::string_view s) {
    std::string out;
    out.reserve(s.size());
    for (unsigned char c : s) {
        if (c < 0x20 || c == 0x7F) {
            out.push_back('?');
        } else {
            out.push_back(static_cast<char>(c));
        }
    }
    // Bound the field — a multi-MB pack name in the log line is its own
    // form of poisoning.
    constexpr std::size_t kMaxLogField = 256;
    if (out.size() > kMaxLogField) {
        out.resize(kMaxLogField);
        out.append("...");
    }
    return out;
}

// Applied to every free-text column reaching Postgres (name/version/description/yaml_source and
// the item equivalents), mirroring license_store.cpp/discovery_store.cpp's sanitize_pg_text — a
// bad byte in a legacy file must not brick the mandatory backfill, and an install()'d pack's YAML
// (attacker-controlled: operator-supplied or network-fetched) is equally untrusted. libpq binds
// text parameters as C-strings, so an embedded NUL would otherwise silently TRUNCATE the stored
// value at that point — the pre-migration `sqlite3_bind_text(..., -1, ...)` had this exact
// truncation behavior too, so U+FFFD replacement here is a strict improvement, not a new risk
// (see product_pack_store.hpp file header).
std::string sanitize_pg_text(std::string_view s) {
    std::string out = sanitize_utf8_strict(s);
    std::size_t pos = 0;
    while ((pos = out.find('\0', pos)) != std::string::npos) {
        out.replace(pos, 1, "\xEF\xBF\xBD");
        pos += 3;
    }
    return out;
}

std::int64_t to_i64(const char* s) {
    if (s == nullptr || s[0] == '\0')
        return 0;
    return static_cast<std::int64_t>(std::strtoll(s, nullptr, 10));
}
bool to_bool(const char* s) {
    return s != nullptr && s[0] == 't';
}
std::string text_col(PGresult* res, int row, int col) {
    return PQgetisnull(res, row, col) ? std::string{} : std::string(PQgetvalue(res, row, col));
}

// ── Migration DDL ────────────────────────────────────────────────────────────

const std::vector<pg::PgMigration>& migrations() {
    // Unqualified DDL: the runner sets search_path to the store schema for the migration txn.
    // Runtime statements below schema-qualify explicitly. `verified` is folded into v1 here —
    // the pre-migration SQLite store patched it in via a raw ALTER TABLE run outside the
    // migration list on every construction (a pre-7.13 compat shim); on Postgres the schema is
    // born fresh, so that shim has no reason to exist.
    static const std::vector<pg::PgMigration> kMigrations = {
        {1,
         "CREATE TABLE product_packs ("
         "  id           TEXT PRIMARY KEY,"
         "  name         TEXT NOT NULL,"
         "  version      TEXT NOT NULL DEFAULT '1.0.0',"
         "  description  TEXT NOT NULL DEFAULT '',"
         "  yaml_source  TEXT NOT NULL,"
         "  installed_at BIGINT NOT NULL DEFAULT 0,"
         "  verified     BOOLEAN NOT NULL DEFAULT FALSE);"
         "CREATE INDEX idx_product_packs_installed ON product_packs(installed_at DESC);"
         "CREATE TABLE product_pack_items ("
         "  pack_id      TEXT NOT NULL REFERENCES product_packs(id) ON DELETE CASCADE,"
         "  kind         TEXT NOT NULL,"
         "  item_id      TEXT NOT NULL,"
         "  name         TEXT NOT NULL DEFAULT '',"
         "  yaml_source  TEXT NOT NULL DEFAULT '',"
         "  PRIMARY KEY (pack_id, item_id));"
         "CREATE INDEX idx_pack_items_pack ON product_pack_items(pack_id);"
         // ADR-0009 erasure-consistency (RbacStore's `revoked_seed_defaults` is the precedent
         // for this shape — a dedicated suppression table, never a plain DELETE an idempotent
         // reseed/backfill would silently undo). `uninstall()` stamps a row here in the SAME
         // transaction as its DELETEs. `migrate_from_sqlite` (retired, #3623) used to consult
         // it before treating an unmatched legacy pack id as fresh content — kept as-is despite
         // that consumer's removal; whether this table is now itself vestigial is a separate,
         // undecided question this removal deliberately does not resolve.
         "CREATE TABLE deleted_pack_ids ("
         "  pack_id    TEXT PRIMARY KEY,"
         "  deleted_at BIGINT NOT NULL);"},
        // migrate_from_sqlite() retired (ADR-0009 fresh-start-by-default, #3623) —
        // sqlite_backfill_source's sole purpose was the backfill idempotency marker,
        // which no longer has a writer. Version-bumped (not edited into v1) because
        // v1 has actually run against real dev/UAT databases — see ADR-0054's Update.
        {2, "DROP TABLE IF EXISTS sqlite_backfill_source;"},
        // F033/#3481: optional client-supplied Idempotency-Key dedup. NULL for every install that
        // doesn't supply one — a plain (non-partial) unique index would work identically here
        // (Postgres already treats every NULL as distinct in a unique index), but the partial
        // form skips indexing the common keyless case.
        {3,
         "ALTER TABLE product_packs ADD COLUMN idempotency_key TEXT;"
         "CREATE UNIQUE INDEX idx_product_packs_idempotency_key ON product_packs(idempotency_key) "
         "WHERE idempotency_key IS NOT NULL;"},
    };
    return kMigrations;
}

// ── Row readers ──────────────────────────────────────────────────────────────

constexpr const char* kPackCols =
    "id, name, version, description, yaml_source, installed_at, verified";

ProductPack read_pack_row(PGresult* res, int row) {
    ProductPack p;
    int c = 0;
    p.id = text_col(res, row, c++);
    p.name = text_col(res, row, c++);
    p.version = text_col(res, row, c++);
    p.description = text_col(res, row, c++);
    p.yaml_source = text_col(res, row, c++);
    p.installed_at = to_i64(PQgetvalue(res, row, c++));
    p.verified = to_bool(PQgetvalue(res, row, c++));
    return p;
}

ProductPackItem read_item_row(PGresult* res, int row) {
    ProductPackItem it;
    int c = 0;
    it.kind = text_col(res, row, c++);
    it.item_id = text_col(res, row, c++);
    it.name = text_col(res, row, c++);
    it.yaml_source = text_col(res, row, c++);
    return it;
}

// Shared by list()/get() — reads a pack's items on the SAME connection the caller already holds
// (no extra pool acquisition per pack; ADR-0012 §2 "one lease per logical operation").
std::expected<std::vector<ProductPackItem>, std::string> read_items_for_pack(
    PGconn* conn, const std::string& pack_id) {
    pg::PgResult res = pg::exec_params(
        conn,
        "SELECT kind, item_id, name, yaml_source FROM product_pack_store.product_pack_items "
        "WHERE pack_id = $1",
        std::vector<std::string>{pack_id});
    if (res.status() != PGRES_TUPLES_OK)
        return std::unexpected(std::string(kProductPackDbErrorPrefix) +
                               "load items failed: " + PQerrorMessage(conn));
    const int rows = PQntuples(res.get());
    std::vector<ProductPackItem> items;
    items.reserve(static_cast<std::size_t>(rows));
    for (int i = 0; i < rows; ++i)
        items.push_back(read_item_row(res.get(), i));
    return items;
}

// ── Hex decode helper ───────────────────────────────────────────────────────

bool hex_decode(const std::string& hex, std::vector<uint8_t>& out) {
    if (hex.size() % 2 != 0)
        return false;
    out.resize(hex.size() / 2);
    for (size_t i = 0; i < hex.size(); i += 2) {
        unsigned int byte = 0;
        auto hi = hex[i];
        auto lo = hex[i + 1];

        auto hex_val = [](char c) -> int {
            if (c >= '0' && c <= '9')
                return c - '0';
            if (c >= 'a' && c <= 'f')
                return 10 + (c - 'a');
            if (c >= 'A' && c <= 'F')
                return 10 + (c - 'A');
            return -1;
        };

        int h = hex_val(hi);
        int l = hex_val(lo);
        if (h < 0 || l < 0)
            return false;
        byte = static_cast<unsigned int>((h << 4) | l);
        out[i / 2] = static_cast<uint8_t>(byte);
    }
    return true;
}

} // namespace

// ── Static helpers ──────────────────────────────────────────────────────────

std::string ProductPackStore::extract_yaml_value(const std::string& yaml, const std::string& key) {
    auto search = key + ":";
    auto pos = yaml.find(search);
    while (pos != std::string::npos) {
        if (pos > 0 && yaml[pos - 1] != '\n' && yaml[pos - 1] != ' ' && yaml[pos - 1] != '\t') {
            pos = yaml.find(search, pos + 1);
            continue;
        }
        auto vstart = pos + search.size();
        while (vstart < yaml.size() && (yaml[vstart] == ' ' || yaml[vstart] == '\t'))
            ++vstart;
        if (vstart >= yaml.size() || yaml[vstart] == '\n')
            return {};
        auto eol = yaml.find('\n', vstart);
        if (eol == std::string::npos)
            eol = yaml.size();
        auto val = yaml.substr(vstart, eol - vstart);
        while (!val.empty() && (val.back() == ' ' || val.back() == '\t' || val.back() == '\r'))
            val.pop_back();
        if (val.size() >= 2 && ((val.front() == '"' && val.back() == '"') ||
                                (val.front() == '\'' && val.back() == '\''))) {
            val = val.substr(1, val.size() - 2);
        }
        if (val == ">" || val == "|")
            return {};
        return val;
    }
    return {};
}

TransactionOutcome ProductPackStore::check_transaction_outcome(pg::PgPool& pool,
                                                                const std::string& xact_id) {
    auto lease = pool.try_acquire_for(kReadTimeout);
    if (!lease)
        return TransactionOutcome::kUnknown;
    pg::PgResult res = pg::exec_params(lease.get(), "SELECT pg_xact_status($1::xid8)",
                                       std::vector<std::string>{xact_id});
    if (res.status() != PGRES_TUPLES_OK || PQntuples(res.get()) == 0)
        return TransactionOutcome::kUnknown;
    if (PQgetisnull(res.get(), 0, 0))
        return TransactionOutcome::kUnknown; // xid too old for the commit log — genuinely unknown
    auto status = text_col(res.get(), 0, 0);
    if (status == "committed")
        return TransactionOutcome::kCommitted;
    if (status == "aborted")
        return TransactionOutcome::kAborted;
    return TransactionOutcome::kUnknown; // "in progress" — still unresolved, or an unrecognized value
}

std::vector<std::string> ProductPackStore::split_yaml_documents(const std::string& bundle) {
    std::vector<std::string> docs;
    std::string::size_type pos = 0;

    // Skip leading whitespace/newlines
    while (pos < bundle.size() && (bundle[pos] == '\n' || bundle[pos] == '\r' ||
                                   bundle[pos] == ' ' || bundle[pos] == '\t'))
        ++pos;

    while (pos < bundle.size()) {
        // Find next "---" document separator (must be at start of line)
        auto sep = bundle.find("\n---", pos);
        std::string doc;

        if (sep == std::string::npos) {
            doc = bundle.substr(pos);
            pos = bundle.size();
        } else {
            doc = bundle.substr(pos, sep - pos);
            pos = sep + 4; // skip "\n---"
            // Skip trailing newline after separator
            while (pos < bundle.size() && (bundle[pos] == '\n' || bundle[pos] == '\r'))
                ++pos;
        }

        // Strip leading "---" if present at document start
        auto trimmed = doc;
        auto first = trimmed.find_first_not_of(" \t\r\n");
        if (first != std::string::npos) {
            if (trimmed.substr(first, 3) == "---") {
                trimmed = trimmed.substr(first + 3);
                // Skip newline after ---
                auto nl = trimmed.find_first_not_of(" \t\r\n");
                if (nl != std::string::npos)
                    trimmed = trimmed.substr(nl);
                else
                    trimmed.clear();
            }
        }

        // Only add non-empty documents
        auto content_start = trimmed.find_first_not_of(" \t\r\n");
        if (content_start != std::string::npos && !trimmed.empty()) {
            docs.push_back(trimmed);
        }
    }

    return docs;
}

// ── Ed25519 signature verification ──────────────────────────────────────────

bool ProductPackStore::verify_signature(const std::string& content,
                                        const std::string& signature_hex,
                                        const std::string& public_key_hex) {
    // Decode hex strings
    std::vector<uint8_t> sig_bytes;
    std::vector<uint8_t> key_bytes;

    if (!hex_decode(signature_hex, sig_bytes) || sig_bytes.size() != 64) {
        spdlog::warn("ProductPackStore: invalid signature hex (expected 128 hex chars / 64 bytes)");
        return false;
    }
    if (!hex_decode(public_key_hex, key_bytes) || key_bytes.size() != 32) {
        spdlog::warn("ProductPackStore: invalid public key hex (expected 64 hex chars / 32 bytes)");
        return false;
    }

    // OpenSSL EVP Ed25519 verification. Single path on every platform
    // — see the #include comment block above for the BCrypt-was-actually-
    // ECDSA-not-Ed25519 history that justifies routing Windows through
    // OpenSSL too.
    EVP_PKEY* pkey =
        EVP_PKEY_new_raw_public_key(EVP_PKEY_ED25519, nullptr, key_bytes.data(), key_bytes.size());
    if (!pkey) {
        spdlog::warn("ProductPackStore: EVP_PKEY_new_raw_public_key (Ed25519) failed");
        return false;
    }

    EVP_MD_CTX* md_ctx = EVP_MD_CTX_new();
    if (!md_ctx) {
        EVP_PKEY_free(pkey);
        return false;
    }

    bool valid = false;
    if (EVP_DigestVerifyInit(md_ctx, nullptr, nullptr, nullptr, pkey) == 1) {
        int rc = EVP_DigestVerify(md_ctx, sig_bytes.data(), sig_bytes.size(),
                                  reinterpret_cast<const unsigned char*>(content.data()),
                                  content.size());
        valid = (rc == 1);
    }

    EVP_MD_CTX_free(md_ctx);
    EVP_PKEY_free(pkey);
    return valid;
}

// ── Construction ─────────────────────────────────────────────────────────────

ProductPackStore::ProductPackStore(pg::PgPool& pool) : pool_(pool) {
    auto lease = pool_.acquire();
    if (!lease) {
        spdlog::error("ProductPackStore: no database connection at construction ({}) — product "
                      "pack persistence disabled",
                      pool_.last_error());
        return;
    }
    if (!pg::PgMigrationRunner::run(lease.get(), kStoreName, migrations())) {
        spdlog::error("ProductPackStore: schema migration failed — product pack persistence "
                      "disabled");
        return;
    }
    // Gate 8 review of F035 (cpp-expert/sre, both MEDIUM): a second, independent line of
    // defence behind the migration runner's own version guard (ApiTokenStore's #3013/#2964
    // precedent — see its constructor comment for the full mechanism). `deleted_pack_ids` was
    // folded into migration v1 rather than shipped as v2 (this store is unshipped — no v1 has
    // ever been recorded against a live database by an earlier binary). If that assumption is
    // ever wrong for a given database (e.g. a persistent dev/CI Postgres instance that already
    // ran a pre-fix build of this branch's v1), the runner sees version 1 already applied and
    // silently skips it, leaving `deleted_pack_ids` missing — this table-presence smoke-read
    // catches that and fails CLOSED (ADR-0012 §1) rather than surfacing as a raw "relation does
    // not exist" on the first uninstall() call.
    pg::PgResult smoke = pg::exec_params(
        lease.get(), "SELECT 1 FROM product_pack_store.deleted_pack_ids LIMIT 0",
        std::vector<std::string>{});
    if (smoke.status() != PGRES_TUPLES_OK) {
        spdlog::error(
            "ProductPackStore: post-migration smoke-read of deleted_pack_ids failed ({}) — the "
            "migration runner reported success but the schema this code expects is not "
            "actually present — refusing to open (ADR-0012 §1 fail-closed)",
            PQerrorMessage(lease.get()));
        return;
    }
    open_ = true;
}

// ── Install ─────────────────────────────────────────────────────────────────

std::expected<std::string, std::string> ProductPackStore::install(
    const std::string& yaml_bundle, ItemInstallFn install_fn, ItemUninstallFn compensate_fn,
    const std::string& idempotency_key, InstallPartialResult* partial_result) {
    if (!open_)
        return std::unexpected(std::string(kProductPackDbErrorPrefix) + "database not open");
    if (!install_fn)
        return std::unexpected("install callback is required");

    auto documents = split_yaml_documents(yaml_bundle);
    if (documents.empty())
        return std::unexpected("no YAML documents found in bundle");

    // Find the ProductPack metadata document
    std::string pack_name;
    std::string pack_version = "1.0.0";
    std::string pack_description;
    int pack_doc_idx = -1;

    for (int i = 0; i < static_cast<int>(documents.size()); ++i) {
        auto kind = extract_yaml_value(documents[i], "kind");
        if (kind == "ProductPack") {
            pack_name = extract_yaml_value(documents[i], "displayName");
            if (pack_name.empty())
                pack_name = extract_yaml_value(documents[i], "name");
            pack_version = extract_yaml_value(documents[i], "version");
            if (pack_version.empty())
                pack_version = "1.0.0";
            pack_description = extract_yaml_value(documents[i], "description");
            pack_doc_idx = i;
            break;
        }
    }

    if (pack_name.empty()) {
        // If no ProductPack document, use the first document's name
        if (!documents.empty()) {
            pack_name = extract_yaml_value(documents[0], "displayName");
            if (pack_name.empty())
                pack_name = extract_yaml_value(documents[0], "name");
        }
        if (pack_name.empty())
            pack_name = "Unnamed Pack";
    }

    // ── Ed25519 signature verification (Issue 7.13) ─────────────────────
    // If the ProductPack document includes a `signature` field, verify it
    // against the content using a public key from `publicKey` in metadata.
    bool pack_verified = false;
    std::string pack_signature;
    std::string pack_public_key;

    if (pack_doc_idx >= 0) {
        pack_signature = extract_yaml_value(documents[pack_doc_idx], "signature");
        pack_public_key = extract_yaml_value(documents[pack_doc_idx], "publicKey");
    }

    if (!pack_signature.empty() && !pack_public_key.empty()) {
        // Build the content to verify: all non-metadata documents concatenated
        std::string content_to_verify;
        for (int i = 0; i < static_cast<int>(documents.size()); ++i) {
            if (i == pack_doc_idx)
                continue;
            if (!content_to_verify.empty())
                content_to_verify += "\n---\n";
            content_to_verify += documents[i];
        }

        pack_verified = verify_signature(content_to_verify, pack_signature, pack_public_key);
        if (pack_verified) {
            spdlog::info("ProductPackStore: signature verified for '{}'",
                         sanitize_for_log(pack_name));
        } else {
            // Signature was present but verification FAILED — reject the pack.
            // A failed signature means the content may have been tampered with.
            spdlog::error("ProductPackStore: signature verification FAILED for '{}' — "
                          "rejecting pack (content may be tampered)",
                          sanitize_for_log(pack_name));
            return std::unexpected("signature verification failed for pack '" + pack_name +
                                   "' — content may have been tampered with");
        }
    } else if (!pack_signature.empty()) {
        // Signature present but no public key — cannot verify, reject
        spdlog::error("ProductPackStore: pack '{}' has signature but no publicKey — "
                      "rejecting pack",
                      sanitize_for_log(pack_name));
        return std::unexpected("pack '" + pack_name +
                               "' has signature but no publicKey — cannot verify");
    } else {
        // No signature field at all — unsigned pack. This is a separate policy
        // question controlled by require_signed_packs_.
        if (require_signed_packs_.load(std::memory_order_relaxed)) {
            spdlog::error("ProductPackStore: pack '{}' is unsigned but signature "
                          "enforcement is enabled — rejecting",
                          sanitize_for_log(pack_name));
            return std::unexpected(
                "pack '" + pack_name +
                "' is unsigned and signature enforcement is enabled "
                "(set --allow-unsigned-packs / YUZU_ALLOW_UNSIGNED_PACKS=1 to bypass)");
        }
        spdlog::info("ProductPackStore: pack '{}' has no signature — installing as unverified",
                     sanitize_for_log(pack_name));
    }

    // F033/#3481: idempotency pre-check, BEFORE install_fn touches any sibling store. A dedup
    // check only at the final persist step would still re-run install_fn against every sibling
    // store on every retry — this is what actually stops that. A prior install with the SAME key
    // and an IDENTICAL bundle is a replay: return its pack id, no sibling-store calls at all. The
    // same key with a DIFFERENT bundle is a plain validation error (never
    // kProductPackDbErrorPrefix — 400, not 503). Fail-closed: any lookup failure here returns
    // before install_fn is ever reached.
    if (!idempotency_key.empty()) {
        auto lease = pool_.try_acquire_for(kReadTimeout);
        if (!lease)
            return std::unexpected(std::string(kProductPackDbErrorPrefix) +
                                   "database unavailable — try again");
        pg::PgResult res = pg::exec_params(
            lease.get(),
            "SELECT id, yaml_source FROM product_pack_store.product_packs "
            "WHERE idempotency_key = $1",
            std::vector<std::string>{sanitize_pg_text(idempotency_key)});
        if (res.status() != PGRES_TUPLES_OK) {
            // Gate 2 review (docs-writer/#3481): unlike list()/get() (read paths, never
            // audited), this failure reaches workflow_routes.cpp's audit_fn as a RAW,
            // unfiltered `detail` — install()'s OTHER db_error messages ("database not
            // open", "failed to persist pack '<name>'") were deliberately kept clean of
            // PQerrorMessage() for exactly this reason; this one wasn't. Log the specific
            // driver detail server-side instead of embedding it in the returned string.
            spdlog::error("ProductPackStore: idempotency lookup failed: {}",
                         PQerrorMessage(lease.get()));
            return std::unexpected(std::string(kProductPackDbErrorPrefix) +
                                   "idempotency lookup failed");
        }
        if (PQntuples(res.get()) > 0) {
            std::string existing_id = text_col(res.get(), 0, 0);
            std::string existing_yaml = text_col(res.get(), 0, 1);
            if (existing_yaml == sanitize_pg_text(yaml_bundle))
                return existing_id;
            return std::unexpected("idempotency key already used with a different request body");
        }
    }

    auto pack_id = gen_id();
    auto now = now_epoch();

    // Install each content document (skip the ProductPack metadata doc). Deliberately NO pool_
    // lease held across this loop — install_fn's callees (InstructionStore/PolicyStore/
    // WorkflowEngine) draw from the SAME shared pool; holding our own lease here would risk
    // starving theirs (docs/postgres-store-playbook.md "never call another store while holding
    // a lease"). See product_pack_store.hpp file header for the full rationale.
    int installed_count = 0;
    std::vector<std::string> errors;
    std::vector<ProductPackItem> items_to_store;

    for (int i = 0; i < static_cast<int>(documents.size()); ++i) {
        if (i == pack_doc_idx)
            continue; // Skip the ProductPack metadata document itself

        auto kind = extract_yaml_value(documents[i], "kind");
        if (kind.empty()) {
            // Try to infer kind from content
            if (documents[i].find("execution:") != std::string::npos ||
                documents[i].find("plugin:") != std::string::npos) {
                kind = "InstructionDefinition";
            } else {
                errors.push_back("document " + std::to_string(i) + ": " + kind_missing_error());
                continue;
            }
        }

        // Delegate to the appropriate store via callback
        auto result = install_fn(kind, documents[i]);
        if (result) {
            auto item_name = extract_yaml_value(documents[i], "displayName");
            if (item_name.empty())
                item_name = extract_yaml_value(documents[i], "name");

            ProductPackItem item;
            item.kind = kind;
            item.item_id = *result;
            item.name = item_name;
            item.yaml_source = documents[i];
            items_to_store.push_back(std::move(item));
            ++installed_count;
        } else if (is_generic_db_error(result.error())) {
            // Governance finding: a genuine origin-store DB/lease failure must abort the whole
            // install immediately, not fall into `errors` — the aggregation below prepends
            // "<kind>: "/"no items installed: " text ahead of the error, which strips the
            // kDbErrorPrefix byte-0 marker the REST layer's is_generic_db_error()/
            // product_pack_error_status() rely on (turning a 503 into a misclassified 400), and
            // in a multi-document bundle where an earlier item already installed, continuing the
            // loop would let the pack persist with this item silently missing. Mirrors
            // uninstall()'s identical origin-store-DB-error-aborts-immediately shape below.
            return std::unexpected(std::string(kProductPackDbErrorPrefix) + "failed to install " +
                                   kind + " item: " + result.error());
        } else {
            errors.push_back(kind + ": " + result.error());
        }
    }

    // #3479: populates the caller-supplied out-param, if any, with per-document detail —
    // called at every return point below that carries an install_fn outcome (total failure or
    // either success path), so a caller always sees which documents failed and why, not just a
    // bare pack id or the first of potentially several failure reasons.
    auto populate_partial_result = [&]() {
        if (partial_result) {
            partial_result->errors = errors;
            partial_result->total_items = installed_count + static_cast<int>(errors.size());
            partial_result->installed_count = installed_count;
        }
    };

    if (installed_count == 0 && !errors.empty()) {
        // Nothing was ever written to Postgres — no rollback needed.
        // Every document's failure reason, not just the first — a bundle with several
        // independently-wrong documents previously only ever told the caller about one.
        std::string joined;
        for (std::size_t i = 0; i < errors.size(); ++i) {
            if (i > 0)
                joined += "; ";
            joined += errors[i];
        }
        populate_partial_result();
        return std::unexpected("no items installed: " + joined);
    }

    // F031/#3481 (gov Gate 2 finding, security-guardian): factored out so every failure path
    // reachable AFTER install_fn has already committed real content into sibling stores —
    // not just the final persist-transaction failure below, but ALSO the duplicate-item-id
    // check immediately following — best-effort compensates every already-installed item, in
    // REVERSE install order (a Policy must be compensated before the PolicyFragment it
    // references, since PolicyStore::delete_fragment refuses while a Policy still references
    // it — forward order would spuriously fail to clean up the fragment). A single item's
    // compensation failing is logged and does not abort compensating the rest. The original
    // (pre-compensation) duplicate-item-id early return orphaned items_to_store just like the
    // bug F031 was written to close — that gap was caught in Gate 2 review of this very PR.
    //
    // Gate 4 review (#3481, unhappy-path, R2): compensate_fn is caller-supplied (same as
    // uninstall_fn) and gets no exception boundary anywhere else in this file either — but
    // unlike uninstall_fn (#3482, deferred, pre-existing), this specific call site is new in
    // this PR and pre-PR the failure paths below always reached workflow_routes.cpp's audit_fn
    // uninterrupted. A throw here must not skip that: caught, logged, and counted the same as
    // an ordinary `false` return so the rest of the reverse-order loop keeps running and
    // install() still returns its normal std::unexpected.
    //
    // Gate 6 review (#3481, architect): items_to_store can carry the SAME item_id twice (the
    // duplicate-item-id case this lambda is called from IS that scenario) — compensate each
    // item_id only once, so a second, already-deleted compensate_fn call doesn't manufacture a
    // false "partial" result/metric for content that was never actually left orphaned.
    //
    // Gate 8 review (#3481, security-guardian — verified with a live repro): keying the dedup
    // set on item_id ALONE is wrong. PolicyStore::create_fragment/create_policy (and the other
    // sibling create_* methods) honor a caller-supplied `id:` YAML field verbatim, so an
    // attacker-controlled bundle can assign the SAME item_id to two documents of DIFFERENT
    // kind (e.g. a PolicyFragment and a Policy) — both install_fn calls succeed (no PK
    // collision, different tables), the duplicate-item-id check below fires, and the item_id-
    // only dedup silently skipped compensating the second one: a real orphan, reported as
    // "compensated 1/1" / metric result="ok". Keyed on (kind, item_id) instead — compensate_fn
    // already dispatches on that same pair, so this matches its actual identity.
    auto compensate_and_fail = [&](const std::string& log_context,
                                   std::string error_message) -> std::unexpected<std::string> {
        // Gate 3 finding (#3479/#3481, cpp-safety): both call sites (duplicate-item-id,
        // final-persist failure) are a "total failure" outcome for #3479's purposes just like
        // the installed_count==0 early return above — populate here so a caller always sees
        // every install_fn error, not just the ones surfaced via the OTHER early return.
        populate_partial_result();
        std::size_t compensated = 0;
        std::size_t attempted = 0;
        if (compensate_fn) {
            std::unordered_set<std::string> already_compensated;
            for (auto it = items_to_store.rbegin(); it != items_to_store.rend(); ++it) {
                if (!already_compensated.insert(it->kind + '\x1f' + it->item_id).second)
                    continue;
                ++attempted;
                bool ok = false;
                try {
                    ok = compensate_fn(it->kind, it->item_id).has_value();
                } catch (const std::exception& e) {
                    spdlog::error(
                        "ProductPackStore: install compensation THREW for {} '{}' after {} "
                        "for pack '{}': {} — orphaned sibling content requires "
                        "manual/operator cleanup",
                        it->kind, sanitize_for_log(it->item_id), log_context,
                        sanitize_for_log(pack_name), sanitize_for_log(e.what()));
                } catch (...) {
                    spdlog::error(
                        "ProductPackStore: install compensation THREW (unknown) for {} '{}' "
                        "after {} for pack '{}' — orphaned sibling content requires "
                        "manual/operator cleanup",
                        it->kind, sanitize_for_log(it->item_id), log_context,
                        sanitize_for_log(pack_name));
                }
                if (ok) {
                    ++compensated;
                } else {
                    spdlog::error(
                        "ProductPackStore: install compensation FAILED for {} '{}' after {} "
                        "for pack '{}' — orphaned sibling content requires manual/operator "
                        "cleanup",
                        it->kind, sanitize_for_log(it->item_id), log_context,
                        sanitize_for_log(pack_name));
                }
            }
            if (metrics_)
                metrics_
                    ->counter("yuzu_server_product_pack_install_compensation_total",
                              {{"result", compensated == attempted ? "ok" : "partial"}})
                    .increment();
        }
        spdlog::error("ProductPackStore: {} for pack '{}' — compensated {}/{} item(s)",
                     log_context, sanitize_for_log(pack_name), compensated, attempted);
        // Gate 6 finding (#3481, compliance-officer): workflow_routes.cpp's audit_fn call
        // passes this returned message straight into the audit `detail` field — without this,
        // an auditor reconstructing a denied install from the audit store alone had no way to
        // tell whether compensation fully succeeded, partially succeeded, or was never
        // attempted (compensate_fn omitted). The kind/item_id of a specific FAILED item stays
        // in the spdlog::error line above only — appending it here would put attacker-supplied
        // YAML content into the audit trail's `detail`, which the not_found/validation-message
        // passthrough above already accepts for OTHER reasons but a raw item_id should not be
        // added to gratuitously.
        if (attempted > 0)
            error_message += std::format(" (compensated {}/{} item(s))", compensated, attempted);
        return std::unexpected(std::move(error_message));
    };

    // Gate 8 review (Fable, external): a bundle whose documents assign the same item id
    // twice would otherwise reach the persist transaction below, violate
    // product_pack_items' (pack_id, item_id) PK, and fail with kProductPackDbErrorPrefix —
    // classified as a genuine DB error, hence a RETRYABLE 503 at the REST layer. This
    // condition is deterministic (the same bundle always duplicates the same id), so a
    // client retry never succeeds and instead re-runs install_fn against every sibling
    // store again on each attempt (no lease held across that loop, see the file header),
    // compounding the F031/F033-tracked orphan risk. Detected here, before any Postgres
    // interaction, and classified as a plain validation error (400, not 503) so a client
    // knows not to retry — this does not change the "fails the whole install" outcome
    // (already the case, see the changelog fragment), only its retryability.
    {
        std::unordered_set<std::string> seen_item_ids;
        for (const auto& item : items_to_store) {
            if (!seen_item_ids.insert(item.item_id).second)
                // Gate 4 finding (#3481, unhappy-path, UP-3): item.item_id can be
                // attacker-controlled arbitrary text for PolicyFragment/Policy documents
                // (unlike InstructionStore, PolicyStore applies no charset check to a
                // caller-supplied `id:` field) — this message reaches BOTH the client
                // response body (no kProductPackDbErrorPrefix, so product_pack_client_message
                // never genericizes it) and the audit `detail` unfiltered. json_escape (the
                // hand-rolled A4-envelope serializer) passes bytes >=0x20 through without
                // UTF-8 validation (pre-existing, documented gap — see on_behalf_guard.hpp's
                // truncation-helper comment, #2500) — invalid UTF-8 in an unsanitized id
                // would ship an invalid-UTF-8 JSON response. sanitize_pg_text (already used
                // throughout this file) fixes both this and the "gratuitous raw content in
                // the audit trail" concern compensate_and_fail's own doc comment raises.
                return compensate_and_fail(
                    "duplicate item id detected",
                    "duplicate item id in bundle: '" + sanitize_pg_text(item.item_id) + "'");
        }
    }

    // Now persist the pack row + its successfully-installed item rows in ONE transaction
    // (parent-before-child for the product_pack_items -> product_packs FK).
    //
    // Gov Gate 5 CHAOS-1/CHAOS-1b (#3481, verified): acquire the write lease OURSELVES first,
    // via try_acquire_for + with_txn_on, rather than the one-call with_txn_for — this is what
    // lets the failure branch below tell apart "the lease was never acquired, the transaction
    // never started" (nothing ambiguous, safe to compensate exactly as before) from "the lease
    // was held and the transaction itself reported failure" (ambiguous — the client-observed
    // failure is not ordered relative to the backend's own commit progress, so it could be a
    // genuine rollback, a still-in-flight commit, OR a lost COMMIT-response ack after Postgres
    // already committed — with_txn_for's single bool return cannot distinguish any of these,
    // and compensating on anything but a genuine rollback would ACTIVELY DELETE real,
    // already-persisted sibling-store content). The existing pool-starvation compensation tests
    // pin the pool's only connection BEFORE calling install() — that failure mode is caught here
    // as a with_txn_lease acquire failure and compensates exactly as before; those tests are
    // unaffected.
    std::string current_xact_id; // captured inside the txn body; empty = no write could have landed
    auto with_txn_lease = pool_.try_acquire_for(kWriteTimeout);
    bool write_lease_acquired = static_cast<bool>(with_txn_lease);
    bool ok = pool_.with_txn_on(std::move(with_txn_lease), [&](PGconn* conn) -> bool {
        // Captured FIRST, before any write: if THIS statement fails, nothing in this
        // transaction could have been written yet, so current_xact_id stays empty and the
        // failure path below treats it as unambiguous without needing a server-side outcome
        // check at all. If it succeeds, the id lets that path ask Postgres the transaction's
        // true fate (committed/aborted/still-unresolved) rather than inferring it from a
        // row-visibility side effect, which CHAOS-1b showed is not a reliable proxy.
        pg::PgResult xid_res = pg::exec_params(conn, "SELECT pg_current_xact_id()::text",
                                               std::vector<std::string>{});
        if (xid_res.status() != PGRES_TUPLES_OK || PQntuples(xid_res.get()) == 0)
            return false;
        current_xact_id = text_col(xid_res.get(), 0, 0);

        // idempotency_key binds via the std::optional<std::string> overload — NOT the plain
        // std::string overload, which would bind an empty key as "" rather than SQL NULL and
        // break the partial unique index's NULL-exemption for every keyless install after the
        // first (F033/#3481).
        pg::PgResult pres = pg::exec_params(
            conn,
            "INSERT INTO product_pack_store.product_packs "
            "(id, name, version, description, yaml_source, installed_at, verified, "
            "idempotency_key) "
            "VALUES ($1,$2,$3,$4,$5,$6::bigint,$7::boolean,$8)",
            std::vector<std::optional<std::string>>{
                pack_id, sanitize_pg_text(pack_name), sanitize_pg_text(pack_version),
                sanitize_pg_text(pack_description), sanitize_pg_text(yaml_bundle),
                std::to_string(now), pack_verified ? "true" : "false",
                idempotency_key.empty() ? std::nullopt
                                        : std::optional<std::string>(
                                              sanitize_pg_text(idempotency_key))});
        if (pres.status() != PGRES_COMMAND_OK)
            return false;

        for (const auto& item : items_to_store) {
            pg::PgResult ires = pg::exec_params(
                conn,
                "INSERT INTO product_pack_store.product_pack_items "
                "(pack_id, kind, item_id, name, yaml_source) VALUES ($1,$2,$3,$4,$5)",
                std::vector<std::string>{pack_id, sanitize_pg_text(item.kind),
                                         sanitize_pg_text(item.item_id),
                                         sanitize_pg_text(item.name),
                                         sanitize_pg_text(item.yaml_source)});
            if (ires.status() != PGRES_COMMAND_OK)
                return false;
        }
        return true;
    });
    if (!ok) {
        if (write_lease_acquired && !current_xact_id.empty()) {
            // The lease was held and this transaction's own id was captured before it failed —
            // this is the ambiguous case. Ask Postgres itself for that xact's true fate rather
            // than inferring it from row visibility (CHAOS-1b: absence alone can't distinguish
            // "aborted" from "not yet committed").
            switch (check_transaction_outcome(pool_, current_xact_id)) {
            case TransactionOutcome::kCommitted:
                // The commit landed; only the ack was lost. Do NOT compensate — that would
                // delete real, already-persisted sibling-store content. Report success.
                spdlog::error(
                    "ProductPackStore: install for pack '{}' ({}) reported a transaction "
                    "failure but Postgres confirms xact {} actually COMMITTED — an ambiguous "
                    "COMMIT-acknowledgment loss, not a real failure. Treating as success; no "
                    "compensation run.",
                    sanitize_for_log(pack_name), pack_id, current_xact_id);
                populate_partial_result();
                return pack_id;
            case TransactionOutcome::kUnknown:
                // Still in progress, too old for the commit log, or the check itself couldn't
                // run. The only safe read is "do not compensate" — never risk deleting content
                // that might actually be there.
                spdlog::error(
                    "ProductPackStore: install for pack '{}' failed to persist AND xact {}'s "
                    "outcome could not be confirmed (still in progress, or the status check "
                    "itself failed) — cannot rule out an eventual commit. Skipping compensation "
                    "as unsafe; this pack id may be a residual orphan requiring manual/operator "
                    "verification.",
                    sanitize_for_log(pack_name), current_xact_id);
                // Gate 3 finding (#3481, cpp-expert): gated on compensate_fn, matching
                // compensate_and_fail's own gating — a direct caller that never supplied
                // compensate_fn never attempted compensation, so this counter (whose own
                // description says it's only emitted when an attempt was possible) should
                // stay untouched for that caller, same as every other emission site.
                if (metrics_ && compensate_fn)
                    metrics_
                        ->counter("yuzu_server_product_pack_install_compensation_total",
                                  {{"result", "partial"}})
                        .increment();
                populate_partial_result();
                return std::unexpected(std::string(kProductPackDbErrorPrefix) +
                                       "failed to persist pack '" + pack_name + "'");
            case TransactionOutcome::kAborted:
                break; // Genuinely rolled back — fall through to compensate as before.
            }
        }
        return compensate_and_fail(
            "failed to persist pack transaction",
            std::string(kProductPackDbErrorPrefix) + "failed to persist pack '" + pack_name +
                "'");
    }

    spdlog::info("ProductPackStore: installed '{}' v{} ({}), {} items, {} errors",
                 sanitize_for_log(pack_name), pack_version, pack_id, installed_count,
                 errors.size());
    populate_partial_result();
    return pack_id;
}

// ── List / Get ──────────────────────────────────────────────────────────────

std::expected<std::vector<ProductPack>, std::string> ProductPackStore::list(
    const ProductPackQuery& q) {
    if (!open_) {
        if (note_read_degrade(metrics_, kReasonStoreNotOpen, g_list_sampler))
            spdlog::warn("ProductPackStore::list: store not open");
        return std::unexpected(std::string(kProductPackDbErrorPrefix) + "database not open");
    }

    auto lease = pool_.try_acquire_for(kReadTimeout);
    if (!lease) {
        if (note_read_degrade(metrics_, kReasonPoolTimeout, g_list_sampler))
            spdlog::warn("ProductPackStore::list: no connection in time ({})",
                        pool_.last_error());
        return std::unexpected(std::string(kProductPackDbErrorPrefix) +
                               "database unavailable — try again");
    }

    int limit = q.limit;
    if (limit <= 0)
        limit = kDefaultListLimit;
    if (limit > kMaxListLimit)
        limit = kMaxListLimit;

    std::string sql =
        std::string("SELECT ") + kPackCols + " FROM product_pack_store.product_packs";
    std::vector<std::string> binds;
    if (!q.name_filter.empty()) {
        sql += " WHERE name LIKE $1";
        binds.push_back("%" + sanitize_pg_text(q.name_filter) + "%");
    }
    sql += " ORDER BY installed_at DESC LIMIT $" + std::to_string(binds.size() + 1);
    binds.push_back(std::to_string(limit));

    pg::PgResult res = pg::exec_params(lease.get(), sql.c_str(), binds);
    if (res.status() != PGRES_TUPLES_OK) {
        if (note_read_degrade(metrics_, kReasonQueryError, g_list_sampler))
            spdlog::warn("ProductPackStore::list: query failed: {}", PQerrorMessage(lease.get()));
        return std::unexpected(std::string(kProductPackDbErrorPrefix) +
                               "list failed: " + PQerrorMessage(lease.get()));
    }

    const int rows = PQntuples(res.get());
    std::vector<ProductPack> out;
    out.reserve(static_cast<std::size_t>(rows));
    for (int i = 0; i < rows; ++i) {
        auto p = read_pack_row(res.get(), i);
        auto items = read_items_for_pack(lease.get(), p.id);
        if (!items) {
            if (note_read_degrade(metrics_, kReasonQueryError, g_list_sampler))
                spdlog::warn("ProductPackStore::list: item read failed for pack '{}': {}", p.id,
                             items.error());
            return std::unexpected(items.error());
        }
        p.items = std::move(*items);
        out.push_back(std::move(p));
    }
    return out;
}

std::expected<std::optional<ProductPack>, std::string> ProductPackStore::get(
    const std::string& id) {
    if (!open_) {
        if (note_read_degrade(metrics_, kReasonStoreNotOpen, g_get_sampler))
            spdlog::warn("ProductPackStore::get: store not open");
        return std::unexpected(std::string(kProductPackDbErrorPrefix) + "database not open");
    }

    auto lease = pool_.try_acquire_for(kReadTimeout);
    if (!lease) {
        if (note_read_degrade(metrics_, kReasonPoolTimeout, g_get_sampler))
            spdlog::warn("ProductPackStore::get: no connection in time ({})",
                        pool_.last_error());
        return std::unexpected(std::string(kProductPackDbErrorPrefix) +
                               "database unavailable — try again");
    }

    std::string sql =
        std::string("SELECT ") + kPackCols + " FROM product_pack_store.product_packs WHERE id=$1";
    pg::PgResult res = pg::exec_params(lease.get(), sql.c_str(), std::vector<std::string>{id});
    if (res.status() != PGRES_TUPLES_OK) {
        if (note_read_degrade(metrics_, kReasonQueryError, g_get_sampler))
            spdlog::warn("ProductPackStore::get: query failed: {}", PQerrorMessage(lease.get()));
        return std::unexpected(std::string(kProductPackDbErrorPrefix) +
                               "get failed: " + PQerrorMessage(lease.get()));
    }
    if (PQntuples(res.get()) == 0)
        return std::optional<ProductPack>{std::nullopt};

    auto p = read_pack_row(res.get(), 0);
    auto items = read_items_for_pack(lease.get(), p.id);
    if (!items) {
        if (note_read_degrade(metrics_, kReasonQueryError, g_get_sampler))
            spdlog::warn("ProductPackStore::get: item read failed for pack '{}': {}", p.id,
                         items.error());
        return std::unexpected(items.error());
    }
    p.items = std::move(*items);
    return std::optional<ProductPack>{std::move(p)};
}

// ── Uninstall ───────────────────────────────────────────────────────────────

std::expected<void, std::string> ProductPackStore::uninstall(const std::string& id,
                                                             ItemUninstallFn uninstall_fn) {
    if (!open_)
        return std::unexpected(std::string(kProductPackDbErrorPrefix) + "database not open");
    if (!uninstall_fn)
        return std::unexpected("uninstall callback is required");

    auto pack_result = get(id);
    if (!pack_result)
        return std::unexpected(pack_result.error());
    if (!*pack_result)
        return std::unexpected("not_found: product pack not found: " + id);
    ProductPack pack = std::move(**pack_result);

    // Remove each contained item from its origin store. No pool_ lease of ours held here — same
    // rationale as install() (see file header). A genuine origin-store DB error aborts the whole
    // uninstall (never delete/tombstone the pack while a contained item may still be live) —
    // not-found/unsupported-kind failures from origin stores that don't yet distinguish the two
    // stay tolerated+logged, matching pre-ADR-0058 behaviour.
    int removed = 0;
    for (const auto& item : pack.items) {
        auto item_result = uninstall_fn(item.kind, item.item_id);
        if (item_result) {
            ++removed;
        } else if (item_result.error().starts_with(kProductPackDbErrorPrefix)) {
            return std::unexpected(std::string(kProductPackDbErrorPrefix) +
                                    "failed to remove " + item.kind + " item '" + item.item_id +
                                    "': " + item_result.error());
        } else {
            spdlog::warn("ProductPackStore: failed to remove {} item '{}': {}", item.kind,
                         item.item_id, item_result.error());
        }
    }

    bool ok = pool_.with_txn_for(kWriteTimeout, [&](PGconn* conn) -> bool {
        // MUST be the first statement in this transaction — see kErasureCoordLockSql's comment.
        pg::PgResult lk = pg::exec_params(conn, kErasureCoordLockSql, std::vector<std::string>{});
        if (lk.status() != PGRES_TUPLES_OK)
            return false;
        pg::PgResult di = pg::exec_params(
            conn, "DELETE FROM product_pack_store.product_pack_items WHERE pack_id = $1",
            std::vector<std::string>{id});
        if (di.status() != PGRES_COMMAND_OK)
            return false;
        pg::PgResult dp = pg::exec_params(
            conn, "DELETE FROM product_pack_store.product_packs WHERE id = $1",
            std::vector<std::string>{id});
        if (dp.status() != PGRES_COMMAND_OK)
            return false;
        // ADR-0009 erasure consistency: stamp the tombstone in the SAME transaction as the
        // deletes (see the deleted_pack_ids schema comment — its original consumer,
        // migrate_from_sqlite, is retired; the tombstone write itself is unchanged).
        pg::PgResult tomb = pg::exec_params(
            conn,
            "INSERT INTO product_pack_store.deleted_pack_ids (pack_id, deleted_at) "
            "VALUES ($1, $2::bigint) ON CONFLICT (pack_id) DO NOTHING",
            std::vector<std::string>{id, std::to_string(now_epoch())});
        if (tomb.status() != PGRES_COMMAND_OK)
            return false;
        return true;
    });
    if (!ok) {
        // F032/#3481: uninstall_fn already removed real sibling-store content (see the file
        // header — no lease of ours was held across that loop, and this txn is what's failing
        // NOW, after that already happened). Accepted, store-scoped residual: no compensating
        // action is possible (nothing to restore), but a retried DELETE self-heals — re-running
        // uninstall_fn against already-gone items is idempotent-ish, then this transaction runs
        // again.
        spdlog::error(
            "ProductPackStore: uninstall failed to persist metadata delete for pack '{}' AFTER "
            "{}/{} sibling item(s) were already removed — pack remains listed as installed, "
            "pointing at deleted/partially-deleted content; retry this DELETE to complete cleanup",
            sanitize_for_log(id), removed, pack.items.size());
        return std::unexpected(std::string(kProductPackDbErrorPrefix) + "uninstall failed");
    }

    spdlog::info("ProductPackStore: uninstalled '{}', removed {} items",
                 sanitize_for_log(pack.name), removed);
    return {};
}

} // namespace yuzu::server
