/**
 * test_pii_ruleset_integrity.cpp — parses and compiles the REAL,
 * build-time-embedded pii_scan ruleset (kEmbeddedPiiRulesJson, generated
 * by scripts/embed_pii_rules.py from content/pii-rules/*.yaml), not just
 * hand-written fixtures.
 *
 * This is the systemic gate several real defects slipped past before this
 * test existed: a pattern that fails to compile under RE2 (unsupported
 * lookahead syntax) is silently dropped by compile_rules() with no
 * failure signal anywhere in the existing fixture-only test suite, and a
 * rule's own `knownTestValues` (real example values the YAML itself
 * declares) were never actually run through the compiled engine by
 * anything. Both classes of bug are exactly what this file exists to
 * catch mechanically, on every build, rather than relying on a reviewer
 * independently compiling the real bundle by hand.
 */

#include <catch2/catch_test_macros.hpp>

#include <nlohmann/json.hpp>
#include <pii_checksum.hpp>
#include <pii_matcher.hpp>
#include <pii_rules.hpp>

#include <format>
#include <string>
#include <string_view>

namespace yuzu::pii {
extern const std::string_view kEmbeddedPiiRulesJson; // generated by embed_pii_rules.py
}

using namespace yuzu::pii;

TEST_CASE("real embedded ruleset: every JSON array item survives parse_rules_json",
         "[pii][ruleset-integrity]") {
    // Independently re-parses the raw JSON to count array items, so this
    // check doesn't rely on parse_rules_json's own bookkeeping to notice
    // its own drops (a JSON-parse-level drop: missing id/pattern, or a
    // per-field type mismatch now caught per-item rather than aborting
    // the whole parse).
    nlohmann::json doc = nlohmann::json::parse(kEmbeddedPiiRulesJson);
    REQUIRE(doc.is_array());
    REQUIRE(doc.size() > 100); // sanity floor — this should never be near-empty

    auto rules = parse_rules_json(kEmbeddedPiiRulesJson);
    INFO("raw JSON array items: " << doc.size() << ", parsed Rule objects: " << rules.size());
    CHECK(rules.size() == doc.size());
}

TEST_CASE("real embedded ruleset: zero rules silently dropped by RE2 compilation",
         "[pii][ruleset-integrity]") {
    auto rules = parse_rules_json(kEmbeddedPiiRulesJson);
    REQUIRE_FALSE(rules.empty());

    std::vector<std::string> bad_rule_ids;
    auto compiled = compile_rules(rules, &bad_rule_ids);

    INFO("bad_rule_ids: " << [&] {
        std::string s;
        for (const auto& id : bad_rule_ids)
            s += id + " ";
        return s;
    }());
    CHECK(bad_rule_ids.empty());
    CHECK(compiled.size() == rules.size());
}

// Every rule's own `knownTestValues` (currently the four generic
// payment-card rules — see content/pii-rules/01-generic.yaml) run through
// the REAL compiled engine end to end: RE2 match against the real
// pattern, then real checksum validation. A value that fails to produce a
// finding for its OWN rule_id means either the pattern doesn't actually
// match the value it claims to validate, or (for a checksummed rule) the
// checksum function rejects a value the rule's own author asserts is
// real — scan_text() drops a checksum failure entirely rather than
// downgrading it, so "a finding for this exact rule_id exists" is already
// proof the checksum passed wherever one is declared.
TEST_CASE("real embedded ruleset: every rule's knownTestValues are detected by the real engine",
         "[pii][ruleset-integrity]") {
    auto rules = parse_rules_json(kEmbeddedPiiRulesJson);
    auto compiled = compile_rules(rules);
    REQUIRE_FALSE(compiled.empty());

    size_t checked = 0;
    for (const auto& r : rules) {
        for (const auto& test_value : r.known_test_values) {
            ++checked;
            auto findings = scan_text(compiled, test_value);
            bool found_own_rule = false;
            for (const auto& f : findings) {
                if (f.rule_id == r.id) {
                    found_own_rule = true;
                    break;
                }
            }
            INFO("rule " << r.id << " knownTestValue " << test_value
                          << " produced " << findings.size() << " finding(s), none matching "
                          << "this rule's own id" << (found_own_rule ? " -- FOUND" : ""));
            CHECK(found_own_rule);
        }
    }
    // If this ever reads 0, either every rule stopped declaring
    // knownTestValues (a real regression in the embed script) or the
    // parse step above silently produced nothing — either way, a test
    // that iterates zero real assertions is not verifying anything.
    CHECK(checked > 0);
}
